### ISSUE TITLE
Semantics of `Vec4Mask::bitmask()` are different in SIMD and scalar code

### ISSUE THREAD

**Issue by cessen** [bitshifter/glam-rs#10]
While adding tests for my work on issue #9 , I discovered that the SIMD and scalar versions of the `bitmask()` function produce different results.  Specifically, the order of the produced bits is reversed.  The SIMD code maps element x to the highest of the four bits in the mask, whereas the scalar code maps it to the lowest of the four bits.

In retrospect, the SIMD version seems a bit more intuitive to me, because it preserves reading order between `x, y, z, w` and listing the bits in binary (e.g. `0b0011`).  It also seems wise to use the SIMD order anyway, since that keeps the SIMD code fast, whereas the ordering doesn't affect the speed of the scalar code at all.

I can knock out a quick fix for this.  However, keeping my tests requires making the `Vec4Mask::new()` function public in the scalar code, and adding a corresponding function for the SIMD code.

Would you like me to go ahead with this and make a PR?

**Comment by bitshifter** [comment]
Ah yep, that would be good thanks! I guess this wasn't covered by the existing tests?

**Comment by cessen** [comment]
Yeah, there were no tests at all for `Vec4Mask`.  I can fill those in too in the same PR if you like. :-)  I'll also check out the other vector widths and fix them if they have the same issue.

**Comment by bitshifter** [comment]
ah right, I was mostly trying to check they were correct via bitmask and the any or all methods.

**Comment by cessen** [comment]
Hmm... things are seeming a little more involved than I thought.  There might be something else going on.  I'll get to the bottom of it.

**Comment by cessen** [comment]
Oh, whoops!  Nope, no bug.  It was completely my fault.  I forgot to swap the order of `x, y, z, w` in the SIMD `Vec4Mask::new()` function.  Sorry for the false alarm.

I can still submit a PR with tests for the `Vec*Mask` functions, though, if you like, since I've already made a lot of them.

**Comment by bitshifter** [comment]
Sure, more test coverage is good.

**Comment by cessen** [comment]
Awesome, I'll submit the PR in a moment.  Sorry again for the false alarm!
