### ISSUE TITLE
Would clamp methods be welcome?

### ISSUE THREAD

**Issue by CleanCut** [bitshifter/glam-rs#100]
A common thing I do in my game projects is clamp vector length to a certain max, min, or both.  Would functionality like that be welcome in `glam`? I am willing to open a PR if this would be useful for glam itself (though I'd likely need assistance with the SIMD part).  I'm thinking something along the lines of (for Vec2, for example):

```rust
    /// Returns a `Vec2` with a length no less than `min` and no more than `max`
    pub fn clamp(&self, min: f32, max: f32) -> Self {
        if self.length() < min {
            self.normalize() * min
        } else if self.length() > max {
            self.normalize() * max
        } else {
            *self
        }
    }

    /// Returns a `Vec2` with a length no more than `max`
    pub fn clamp_max(&self, max: f32) -> Self {
        if self.length() > max {
            self.normalize() * max
        } else {
            *self
        }
    }

    /// Returns a `Vec2` with a length no less than `min`
    pub fn clamp_min(&self, min: f32) -> Self {
        if self.length() < min {
            self.normalize() * min
        } else {
            *self
        }
    }
```

### Additional References
- [`ClampVectorSize` Blueprint Node in Unreal Engine 4](https://docs.unrealengine.com/en-US/BlueprintAPI/Math/Vector/ClampVectorSize/index.html)
- [`Vector3.ClampMagnitude` in Unity](https://docs.unity3d.com/ScriptReference/Vector3.ClampMagnitude.html)
- [`Vector2 clamped` in Godot](https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-clamped)

**Comment by CleanCut** [comment]
A real-world example: I'm clamping player velocity to a max value [here](https://github.com/CleanCut/punchball/blob/fcc5a605de75ed0824c326ac67a25aa5ca6dd6f9/src/player/mod.rs#L226-L229) in a little showcase I'm making to demonstrate using gamepads to drive 2D sprites around.

![punchball-0 1 0](https://user-images.githubusercontent.com/5838512/100318682-ad4e3a00-2f7b-11eb-84c1-2617795a3416.gif)

**Comment by bitshifter** [comment]
Hey there. I'm not sure how common it would be so I'll leave this open for a bit to see if it's something others also want.

A few thoughts about you current proposal, it might be good to name it `clamp_length`. I would assume that `clamp` was going to clamp individual elements in the vec to be withing the range.

It is likely more efficient to calculate the length (or even the squared length) once and only once, e.g.

```
pub fn clamp(&self, min: f32, max: f32) -> Self {
    let length_sq = self.length_squared();
    if length_sq < min * min {
        self * (length_sq.sqrt() * min)
    } else if length_sq > max * max {
        self * (length_sq.sqrt() * max)
    } else {
        *self
    }
}
```
It's probably not worth worrying too much about writing a SIMD version. `length_squared` has a SIMD implementation already via `dot`, but it's not hugely faster, nor is the SIMD sqrt, at least not in x86.

**Comment by CleanCut** [comment]
👍 I opened https://github.com/bitshifter/glam-rs/pull/101 with your approach to the conditional-handling.

**Comment by CleanCut** [comment]
> ### Additional References
> 
> - [`ClampVectorSize` Blueprint Node in Unreal Engine 4](https://docs.unrealengine.com/en-US/BlueprintAPI/Math/Vector/ClampVectorSize/index.html)
> - [`Vector3.ClampMagnitude` in Unity](https://docs.unity3d.com/ScriptReference/Vector3.ClampMagnitude.html)
> - [`Vector2 clamped` in Godot](https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-method-clamped)

I added some reference links to equivalent functionality I've seen or used in the past.

**Comment by bitshifter** [comment]
A couple of things that need to be considered:

* What should happen when a zero length vector is clamped? In `glam` `normalize` does not handle zero length vectors, the onus is on the user to check for zero length if they think that is a possibility. If normalize is called on a zero length vector then a divide by zero will occur. There are suggestions for adding a checked variant of `normalize` in #7. Most likely this is the approach `clamp_length` should take as if the vector is zero length it has no known direction.

* Should there be any special handling of min > max? Unreal reorders the parameters if min > max, The new `clamp` in Rust asserts that the order is valid.

**Comment by bitshifter** [comment]
To be clear I think I'm OK with adding these, they're just a bit on the back burner with my other refactor going on. If the code duplication is a pain when making changes, there are a few things where the implementation has been done in a macro, e.g. `is_normalized`.

**Comment by CleanCut** [comment]
>     * What should happen when a zero length vector is clamped?

>     * Should there be any special handling of min > max?

In general, I'll follow whatever guideline you think I should follow. In the absence of a guideline, I'd lean towards what seems to be the de-facto policy: doing everything unchecked (and no special handling), and worry about adding checked versions later if there's popular demand for them.

I'm fine maintaining the duplicated code in #101 until you feel it's ready to unify into some macro.

**Comment by bitshifter** [comment]
Merged, thanks!
