### ISSUE TITLE
Add GLSL doc aliases to functions.

### ISSUE THREAD

**Issue by XAMPPRocky** [bitshifter/glam-rs#105]
Some of the functions that perform the same operations from GLSL have different names in `glam`. It would be nice if the names for these operations were added as doc aliases so for example if I search `mix`, I would get results for `lerp` functions.

### Example
```rust
#[doc(alias = "mix")]
fn lerp() {}
```

**Comment by bitshifter** [comment]
Sounds like a great idea. Feel free to make a PR for anything you think would be useful

**Comment by bitshifter** [comment]
Turns out this was only stabilized in Rust 1.48.0 so it would require bumping glam's MSVR (currently 1.36.0). I might wait until there are some other new features I want to use before doing that.

**Comment by XAMPPRocky** [comment]
You could also add them behind a `cfg_attr` because docs.rs always builds with a nightly version of rust, so they'd be available there. E.g.

```rust
#[cfg_attr(docsrs, doc(alias = "mix"))]
fn lerp() {}
```
