### ISSUE TITLE
Add/Subtract Traits for vecs

### ISSUE THREAD

**Issue by DGriffin91** [bitshifter/glam-rs#107]
It appears that add/subtract operator traits are only implemented for when lhs & rhs are the same type, but multiply/divide is implemented for more types.

For example, this works: `Vec3::one() * 3.0`
But this does not: `Vec3::one() + 3.0`

Is there something blocking this functionality, or some reason this shouldn't be implemented? I'm glad to help write implementations/tests if appropriate.

Thanks for all your work on this project!

**Comment by bitshifter** [comment]
No real reason other than they don't really make sense mathematically, but as a programming convenience sure that could make sense. The only other negative I think is it might be a bit surprising, I try to be mostly explicit with glam. To be it would be slightly unexpected that you could add a scalar to a vector. Is this something your have found is supported in other libraries?

**Comment by DGriffin91** [comment]
I see how mathematically it is odd. I've mostly run into the issue recently a bunch while converting shadertoy shaders to rust-gpu. 

GLSL supports it, so it gets used in GLSL shaders quite a bit. I come from a Python background and Python's Numpy also supports it.

I understand if it feels like it's not explicit enough and respect whatever decision is made. Since my backround has been with GLSL and Numpy I have assumed that this is a typical feature. I have since learned that it's not a given. (AFIK Ultraviolet & nalgebra do not support it)

I think adding a float to a vec is often done when the vec doesn't really represent a vector, or even a point.
