### ISSUE TITLE
Vector * Matrix multiplication

### ISSUE THREAD

**Issue by Boscop** [bitshifter/glam-rs#112]
It would be nice to have:
- [ ] Vector * Matrix multiplication (vector on the left side, without having to invert the matrix to be able to do the multiplication).
- [x] Matrix truncation like `mat3(mat)` in GLSL (where `mat` is a `mat4`), e.g. via `From<Mat4> for Mat3`.

Currently I have to write:
`mat3(view.x_axis.truncate(), view.y_axis.truncate(), view.z_axis.truncate()).transpose() * v` 
but in GLSL it's `v * mat3(view)`, much shorter and I'd prefer to write it shorter in Rust as well :)

**Comment by Boscop** [comment]
Also it would be nice to have this method on `f32`:
`fn extend(self, y: f32) -> Vec2`.

**Comment by bitshifter** [comment]
I'm happy to add matrix truncation, either via From or as an explicit method, I'd do that sometime soon.

As for vector * matrix multiplication, what do you expect to happen here, implicitly transpose the matrix and perform the multiplication? My preference is to stick with column major conventions. I am not that familiar with glsl, is it row major?

**Comment by Boscop** [comment]
> As for vector * matrix multiplication, what do you expect to happen here, implicitly transpose the matrix and perform the multiplication? My preference is to stick with column major conventions. I am not that familiar with glsl, is it row major?

No transposition, that's only in my Rust code above because I have to write `mat * v` instead of being able to write `v * mat`. In GLSL it's column-major and when you write `v * mat` it will treat `v` as row vector, and `mat * v` will treat `v` as column vector, but `mat` stays the same.

**Comment by bitshifter** [comment]
I mean internally the matrix is transposed to perform the vector multiply, which has a cost. If the user is performing the transpose themselves then it is clear that the transpose happens, if it happens as part of the library it's less clear. For scalar code, the transpose can happen as part of the multiply, for SIMD it's fastest to transpose the matrix columns and then do the vector multiply (again I'm talking internal to the math library here). It's been a while since I did this, but that is my recollection.

Do you know if HLSL also supports something similar?

If I have a vector v and matrices A and B, if I multiply vAB I assume it would be equal to BAv in GLSL?

**Comment by bitshifter** [comment]
Adding some links for this discussion:

HLSL: https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-per-component-math
GLSL: https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf#vector-and-matrix-operations

**Comment by bitshifter** [comment]
Performance aside, I think I'll sit on this one for a while and see where things go with rust-gpu. My feeling is supporting both row vector and column vector multiplication could be confusing for people, especially if they don't have a strong grasp of linear algebra which many game devs don't (which is fine and I want glam to be approachable for people who don't strong math background). Limiting glam to one style removes a potential source of confusing IMO. Supporting both is not something I've seen commonly supported in CPU math libraries either. However, if there is a lot of demand for this coming from the rust-gpu users, if it's a large barrier for porting shaders over from GLSL/HLSL I guess I could be swayed. For now I'd like to leave this open for any further discussion from interested parties.

**Comment by aloucks** [comment]
Having the compiler prevent you from applying the operation in the wrong order is a feature IMO. Implicit transpose seems like a bad idea.

**Comment by bitshifter** [comment]
After sitting on this for a long time, there haven't been any other requests for this, my feeling is I'd rather not add an implicit transpose depending on order of operations.
