### ISSUE TITLE
Support approx comparisons

### ISSUE THREAD

**Issue by eterevsky** [bitshifter/glam-rs#115]
Right now it seems like glam does not provide any good way for checking approximate equality of its values in unit tests. Would it make sense to implement the traits from the [approx](https://docs.rs/approx) crate to be able to use its assertions?

**Comment by bitshifter** [comment]
glam did originally implement approx a while back, but I felt that approximate float comparisons should be native to glam instead of using the approx crate (see #6). glam internally has asserts the are used for self testing. Would it be useful to expose those or would you prefer it if approx support was just added back again?

**Comment by eterevsky** [comment]
Right now there is no easy way to check equality of glam vectors in a unit test, other than by doing something like `assert!((vec1 - vec2).length() < EPSILON)`, which sucks because you don't even get a good error message when the assertion fails. So both exposing `assert_approx_eq!` and supporting approx would be a huge step forward.

I don't have strong preferences regarding which way to go. approx seems like a more natural choice because it is already used in many crates and it also supports relative comparison. But I can understand it if you would like to keep the dependencies to a minimum. One option would be to support approx only behind a feature, so that it's only included if it is needed.

**Comment by bitshifter** [comment]
Any reason you can't use https://docs.rs/glam/0.11.2/glam/struct.Vec3.html#method.abs_diff_eq instead of writing your own comparison with epsilon?

**Comment by eterevsky** [comment]
Oh, I didn't know it was there, thank you!

But the issue with a good error message in unit test still stands: it would be nice to print the values if the assertion failed.

**Comment by bitshifter** [comment]
For sure! I have macros in the tests for glam that do this, I'll look at either implementing approx or exposing the macros I'm using.
