### ISSUE TITLE
Use Hash & Eq for Vecs

### ISSUE THREAD

**Issue by Byteron** [bitshifter/glam-rs#123]
I was wondering if there is a specific reason why all of glams vec types do not derive Hash and Eq.
That would allow for them to be used e.g. as HashMap keys, which can be very beneficial in Game Dev.

**Comment by bitshifter** [comment]
Mostly because `f32` doesn't support them in Rust. I'm away for a few weeks, so won't be able to respond further until I return.

**Comment by bitshifter** [comment]
This post describes the issues with supporting `Hash` and `Eq` for `f32` and `f64` https://internals.rust-lang.org/t/f32-f64-should-implement-hash/5436/33. All of these points apply to vectors of `f32` and `f64` as well. I could add support for the integer types, I would be reluctant to add them for float types because I don't think there's one solution that would satisfy all users.

**Comment by Byteron** [comment]
Just for integer types would already be helpful I think.

**Comment by alec-deason** [comment]
I took a shot at this for i32/u32 types in #134

**Comment by bitshifter** [comment]
@Byteron what is your use case for adding `Vec` types to a hashmap? I am reluctant to add `Hash` and `Eq` for float vector types for the same reasons float types don't support them in Rust, but perhaps there are some general purpose utilities that could be added to assist with this. It comes down to why people want to put vectors in hash maps though.

**Comment by Byteron** [comment]
@bitshifter I want to be able to find entities by their position in a game.
That mean either a `HashMap<IVec2, Entity>` or looping through all of them and compare `entity_position == target_position`.
The HashMap clearly is the faster option, but both would need at least `Eq`. HashMap would also need `Hash`.

Also, finding something by it's position is very common in game dev, so I will not be the only one benefiting from this.

**Comment by bitshifter** [comment]
@Byteron  Are you using the `IVec2` as some kind of grid square lookup, or the actual entity position? `Eq` and `Hash` are supported for `IVec2` now that's to @alec-deason.

**Comment by Byteron** [comment]
Both, I guess?
I mean I'm working with bevy so the actual position that is taken for rendering is a Vec3 in Transform.
But I do use IVec2 both for key in a HashMap (grid lookup) as well as Component for making the entities position (in the grid).

**Comment by bitshifter** [comment]
Going to close this for now. Given Rust doesn't support Hash and Eq for f32 and f64 I don't want to in vectors of those types in glam. Support for int types is hopefully sufficient.
