### ISSUE TITLE
u64 and i64?

### ISSUE THREAD

**Issue by damccull** [bitshifter/glam-rs#125]
Hello,
I see you have f64 support alongside the 32bit int types. I'm interested in using 64 bit int types in a game. Are you planning to support these in the future?

**Comment by bitshifter** [comment]
I didn't have any plans to support them, until now no one has asked for them. What are you doing that needs numbers that large? I'm away for a few weeks and won't respond further until I'm back.

**Comment by damccull** [comment]
I want to represent a galaxy from end to end without resorting to tricks like subgrids and having to change grids when moving from one part of the galaxy to another and without  needing to worry about following point precision. Even with i64 I still think I'll need to scale the galaxy down. This may not be a feasible idea anyways but I want to try.

I'm only asking about the data types here in hopes they'd be trivial to add, but if it will require significant work I will make due with f64 or i32 and just use zoning tricks when necessary.

**Comment by bitshifter** [comment]
They're not entirely trivial, pretty simple but then it's a bit more code to maintain. I would prefer to hold off until there is more demand.

**Comment by damccull** [comment]
Sure, no worries. Thanks for considering it. I'll work around it for now. Good day!

**Comment by rsaarelm** [comment]
I just stopped using glam for doing Advent of Code solutions because I just realized the more advanced tasks require 64-bit integer vectors.

**Comment by rsaarelm** [comment]
https://adventofcode.com/2022/day/15 , the final result asks for multiplying seven-digit x and y coordinates together for the answer, and if you run it without realizing you need to cast to 64 bits and without overflow checks on, you'll get a garbage answer. In retrospect, it's a weird corner case and not really dealing with geometry anymore, so I ended up sticking with glam after all.
