### ISSUE TITLE
Changes to #[repr(simd)] in nightly break XYZ structs on SPIR-V targets

### ISSUE THREAD

**Issue by Arc-blroth** [bitshifter/glam-rs#132]
Since https://github.com/rust-lang/rust/pull/80652, `#repr(simd)]` types on nightly Rust are now required to have a power-of-two size. This change breaks `glam::core::storage::XYZ` and everything that depends on it on SPIR-V targets:
```
error[E0075]: SIMD vector length must be a power of two
    --> .cargo\registry\src\github.com-1ecc6299db9ec823\glam-0.12.0\src\core\storage.rs:12:1
     |
  12 | / pub struct XYZ<T> {
  13 | |     pub x: T,
  14 | |     pub y: T,
  15 | |     pub z: T,
  16 | | }
     | |_^
  error: monomorphising SIMD type `XYZ<f32>` of non-power-of-two length
```
Whether or not non-power-of-two support for SIMD types is coming back is still [being discussed](https://github.com/rust-lang/stdsimd/issues/63), so it's possible that someone will re-add non-power-of-two support in the future. For now though, this issue would make it hard for downstream consumers like [EmbarkStudios/rust-gpu](https://github.com/EmbarkStudios/rust-gpu/) to move to the latest nightly.

**Comment by bitshifter** [comment]
Thanks for the heads up @Arc-blroth!

**Comment by workingjubilee** [comment]
Whoops! Our bad.

Going to figure out how to fix this.
