### ISSUE TITLE
Consider adding from_translation

### ISSUE THREAD

**Issue by John-Nagle** [bitshifter/glam-rs#135]
There are functions for creating matrices from a scale and an angle, but not from a translation. Had to work around this by writing

```
//  Vec2 -> Mat3 translation. This should be part of Glam.
fn from_translation(trans: Vec2) -> Mat3 {
    Mat3::from_cols_array(&[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, trans.x, trans.y, 1.0])
}
```
Suggest adding such functions to Mat3 and Mat4.

**Comment by John-Nagle** [comment]
That was quick! Thanks!

**Comment by bitshifter** [comment]
It was an easy one :)
