### ISSUE TITLE
Vec2.angle_between() return NaN when one Vec2 is at (0,0)

### ISSUE THREAD

**Issue by SamJBarney** [bitshifter/glam-rs#139]
Ran into this issue when trying to calulate the angle a vec2 was at compared to the origin. If either vec2 is at the origin (0,0), then `angle_between` returns a NaN. This also occurs with Vec3.

**Comment by aloucks** [comment]
It's a `2D` vector, not a point. `Vec2(0, 0)` has a length of zero which results in a divide-by-zero when calculating the angle.

There is a conversation [here about adding a Point](https://github.com/bitshifter/glam-rs/issues/133) type.

**Comment by bitshifter** [comment]
I suppose a point type might help with this specific case where something is clearly a point (i.e. the origin) as a point type wouldn't support the angle_between operation, but I imagine someone could easily end up trying to call `angle_between` on a zero length vector.

A vector with no magnitude cannot have a direction so I am not sure what the expectation here would be in this case. We could check the inputs are non zero length but that's a cost that everyone will have to pay even if their inputs are non zero. My inclination would be to improve the documentation of these methods to state that the vectors must have a magnitude and I can add a `glam_assert` to check that is the case.

**Comment by bitshifter** [comment]
I've added a bit more detail to the documentation of these methods that they must be non zero. I'll leave it at that for now.
