### ISSUE TITLE
Perhaps refer users to Rust's f32 primitive's to_radians() in Quat functions' documentation?

### ISSUE THREAD

**Issue by TheLeonsver1** [bitshifter/glam-rs#143]
I'm a new user of the rust language and I didn't know the functions to convert between angles and radians existed on the math primitives while trying to use the bevy engine which is using glam's types and functions,

the documentation currently says for example: 
`Creates a quaternion from the angle (in radians) around the z axis.` 
it might be cool if it could also say on a new line something like, `you can convert angles to radians using f32::to_radians()` or something like that. thank you for considering it :).

**Comment by bitshifter** [comment]
My only reservation is that there are _a lot_ of places in glam with angle parameters, so this could add quite a bit of noise to the documentation. Perhaps there is a suitable introductory place where I could mention this?

**Comment by bitshifter** [comment]
I've added a mention of angles being in radians and being able to use to_radians in the main lib docs, rather than on every method. Hopefully that's a slight improvement.

**Comment by TheLeonsver1** [comment]
Thank you very much!
