### ISSUE TITLE
Read columns and rows of a matrix

### ISSUE THREAD

**Issue by emilk** [bitshifter/glam-rs#145]
It would be very useful with `fn col(col: usize) -> Vec4` to read a specific column of a matrix. Currently this must be done with the cumbersome `m.to_cols_array_2d()[col].into::<Vec4>()`.

Same for reading a specifc row.

**Comment by bitshifter** [comment]
There is currently some commented out code to do this (e.g. https://github.com/bitshifter/glam-rs/blob/master/src/mat4.rs#L249-L275), so it's a pretty easy PR :)

Rows are a bit trickier, well not that tricky but obviously it will return a temporary which is different to the cols version. There's the possibility of using `Index` for cols as well, but I guess cols is in-keeping with the other explicitly named methods on the matrix type.
