### ISSUE TITLE
Is it possible to add functionality similar to float vectors to integer vectors? 

### ISSUE THREAD

**Issue by TheLeonsver1** [bitshifter/glam-rs#147]
VecN and DVecN implement the macro `impl_vecn_float_methods` which adds functionality like `distance()` and `distancesq()` and more, is it perhaps possible to add such functionally to IVecN and UVecN? thank you for considering!

**Comment by bitshifter** [comment]
Most of the methods in `impl_vecn_float_methods` don't make sense for integer types. Was there anything else besides `distance` and `distance_squared`?

Why do you need/want them?

**Comment by bitshifter** [comment]
My main concern with doing this is glam needs to make some choices about how this work, which may or may not be the correct choice depending on what individual game in trying to achieve.

Specifically, `distance` calls `length` which calls `sqrt` which is a float operation. So the IVecN/UVecN needs to be cast to float to perform the `sqrt`. When casting back to integer glam would need to decide to if the result should be `floor`, `round` or `ceil` when casting to integer. What is the appropriate choice depends on what it is being used for. For that reason I would be reluctant to add this to glam and would suggest games write their own integer distance extension methods that do what is appropriate for them.

The caveat to the above I guess would be if there is a really super common use case for this that I am not familiar with.

**Comment by TheLeonsver1** [comment]
I think that if you implement this(distances for example) you should just return an `f32` and the user can use that however they want. I don't think you need to convert that to an integer yourself, I think that's unnecessary, I just would prefer to not cast a `UVec2` to a `Vec2` to get the distance between 2 `UVec2`s (or straight up converting usizes/u32s to f32s haha), and I haven't checked what other functions exist in the macro, but I think normalizing might be useful too to someone(even if you return a Vec2 to make the normalized's length 1 - and not an IVec/Uvec). 
It's 4:30 am here so I'm not awake enough to think about this clearly, hopefully, I haven't spouted nonsense, and tomorrow I'll be able to think better.

**Comment by TheLeonsver1** [comment]
Oh i haven’t read hour comment until it’s end, my use case is going through a 2d grid of chunks and applying a brute force voronoi algoithm, so i want to find which seed is the closest to the current grid position, i don’t know if this would be a common use case, i’m sorry.

**Comment by TheLeonsver1** [comment]
so basically currently it looks like this:
```rust
for i in 0..10 {
        points.push(UVec2::new(
            rng.gen_range(0..chunk_grid_length as u32),
            rng.gen_range(0..chunk_grid_length as u32),
        ));
    }
    let chunk_world = ChunkWorld::default();
    for y in 0..chunk_grid_length {
        for x in 0..chunk_grid_length {
            let mut min_distance = f32::MAX;
            let mut closest_p_index = 0;
            for p in 0..points.len() {
                let distance = points[p].as_f32().distance(Vec2::new(x as f32, y as f32));
                if distance < min_distance {
                    min_distance = distance;
                    closest_p_index = p;
                }
            }
        }
    }
```
let distance = points[p].as_f32().distance(Vec2::new(x as f32, y as f32));

**Comment by bitshifter** [comment]
I feel that this wouldn't be common enough a use case to add to the library. For example, I've seen other math libraries support this kind of thing by converting to float internally then rounding retuning an int. That wouldn't work for your use case above however. The point being that with this kind of functionality what is correct depends on the particulars of the project using it and therefore it's not general purpose enough to add to the library. Perhaps others will appear who ask for something similar but for now I'm going to close this off.
