### ISSUE TITLE
no_std broke in 0.13.0

### ISSUE THREAD

**Issue by sanbox-irl** [bitshifter/glam-rs#149]
Hello! A lib.rs like this:

```
#![no_std]
```

and a cargo.toml like this:

```
[dependencies]
glam = { version = "0.13.0", default-features = false, features = ["libm"] }
```

will result in lots of errors about missing types on f32. such as:
```
error[E0599]: no method named `copysign` found for type `f32` in the current scope
   --> C:\Users\jjspi\.cargo\registry\src\github.com-1ecc6299db9ec823\glam-0.13.0\src\vec3.rs:218:36
    |
218 |             let sign = (1.0 as $t).copysign(self.z);
    |                                    ^^^^^^^^ method not found in `f32`
```
    
Looks like libm isn't working right in these macros.

rolling back to 0.12 works just fine though

**Comment by sanbox-irl** [comment]
strangely, compiling the crate itself is no problem with no default features and libm as a feature. I'm not exactly sure what's going on there. I could be missing something?

**Comment by bitshifter** [comment]
I have encountered this before, with the rust-gpu project. It is a bit odd. This was the problem last time - https://discord.com/channels/750717012564770887/750717499737243679/776804637122363433.

Maybe I need to add some test project to the CI just to catch when this break.

**Comment by bitshifter** [comment]
Fortunately this was just fixed by a rust-gpu PR. I've added a standalone no_std project to tests to try catch this in the future.

**Comment by sanbox-irl** [comment]
Thank you very much!!
