### ISSUE TITLE
Swizzle support

### ISSUE THREAD

**Issue by bitshifter** [bitshifter/glam-rs#15]
It would be good to support generic swizzles.

Ideally this would support swizzling to return the same size vector but a long term goal would be to provide swizzling into a vector of a different size, smaller or larger.

The problem with SSE2 shuffles is the mask needs to be constant. The intrinsic itself is not a `const` function so I can't provide a method that will take a mask or at least I don't think that's possible. There are a couple of alternatives: 

- Generate shuffle methods for all possible permutations. This is what pathfinder does but that's 255 methods for swizzling a `Vec4` to another `Vec4`, potentially more if swizzling to a different size is supported. My main concern with this approach is making sure it doesn't make a mess of the docs.
- Use macros - the underlying `__m128` is accessible so I think a macro solution would be possible. I would probably provide `vec4_swizzle`, `vec3_swizzle`, and `vec2_swizzle` so that the type is known and the number of lanes specified in the macro could be used to specify the output size.

**Comment by Lokathor** [comment]
Just write a program to auto-generate all the swizzles

it's only [4000 lines of code give or take](https://github.com/Lokathor/hektor/blob/master/src/swizzle4.rs) once the program prints it out ;3

**Comment by bitshifter** [comment]
I wrote a program to generate all the swizzles :)
