### ISSUE TITLE
New crates.io release

### ISSUE THREAD

**Issue by XAMPPRocky** [bitshifter/glam-rs#161]
Hey, I was wondering if it would be possible to release a new version of glam? Normally I would just use `[patch.crates-io]`, however `[patch]` doesn't handle when the patched version has a different feature than the original (in this case `spirv-std` since it was made an optional dependency), so currently we can't enable the new glam patch without a published version that has the `spirv-std` feature.

**Comment by bitshifter** [comment]
Done, the new version is 0.14.0.
