### ISSUE TITLE
New crates.io release?

### ISSUE THREAD

**Issue by HalfVoxel** [bitshifter/glam-rs#172]
Hey, I was wondering if it would be possible to release a new version of glam?
We are pinning some things to specific revisions, but it would be nice with a new version number to use, especially for releasing things that depend on glam.

**Comment by bitshifter** [comment]
What are you after that's unreleased? I'm still bike shedding on some of the new types at the moment.

**Comment by HalfVoxel** [comment]
Hi

Thanks for the fast response!
I'm not 100% sure what we depend on. I think the most important things are the EulerRot type and the updated spirv-std version.

**Comment by bitshifter** [comment]
Done!

**Comment by HalfVoxel** [comment]
Awesome! Thanks!
