### ISSUE TITLE
Overflow error in assert in glam 0.15

### ISSUE THREAD

**Issue by HalfVoxel** [bitshifter/glam-rs#180]
After updating to 0.15 we get this error:
![image](https://user-images.githubusercontent.com/1144597/118264088-77fcc080-b4b7-11eb-8565-00b14b95e55c.png)

which seems like a bug to me?

**Comment by HalfVoxel** [comment]
I haven't traced back exactly where this is coming from. But I think this target is building for spirv.

**Comment by HalfVoxel** [comment]
It seems like pretty much all the new asserts fail.

**Comment by bitshifter** [comment]
It's effectively a compile time assert, so what it's saying is the alignment of `DAffine2` is not 8.

How are you compiling for spriv? It's not something I'm doing regularly.

**Comment by bitshifter** [comment]
Manage to repro it. Not sure why it's failing, I guess align_of for spriv is something unexpected

**Comment by bitshifter** [comment]
Published 0.15.1 which hopefully fixes this. Size and alignment was reported to be 16 for the type I checked (`Vec3`) which is quite different to CPU targets.

Let me know if that works for you. If it doesn't it will have to wait until tomorrow :)

**Comment by HalfVoxel** [comment]
Thanks for the quick update! It works now :)
