### ISSUE TITLE
Missing impls on Affine3A

### ISSUE THREAD

**Issue by cessen** [bitshifter/glam-rs#182]
In changing my path tracer to use `Affine3A` instead of `Mat4`, I discovered a couple of missing impls that I was using from `Mat4`:

- `Affine3A + Affine3A` (simple component-wise addition)
- `Affine3A * f32` (scale each component by a scalar float)

They're easy enough to work around by just converting to/from `Mat4`, and I'm using a wrapper type anyway, so it wasn't a big deal for me.  But it might be annoying for people who are using the type directly.

**Comment by bitshifter** [comment]
No problem adding these

**Comment by cessen** [comment]
Awesome, thanks!
