### ISSUE TITLE
project function

### ISSUE THREAD

**Issue by TCROC** [bitshifter/glam-rs#191]
It would be nice if there was a function for projecting from one vector onto another normalized vector.  Here's an example code snip that I implemented inside the project:

```rs
trait Vec3Project {
    fn project(self, vector_to_project_onto: Self) -> Self;
}

impl Vec3Project for Vec3 {
    fn project(self, vector_to_project_onto: Self) -> Self {
       self.dot(vector_to_project_onto) * vector_to_project_onto     
    }
}
```

An example of where it would be useful can be found at this repo: https://github.com/ForesightMiningSoftwareCorporation/bevy_transform_gizmo

And here is the video of it in action:

https://user-images.githubusercontent.com/2632925/119217311-33ac8a00-ba8e-11eb-9dfb-db0b9c13cd84.mp4

NOTE: That repo itself doesn't implement that function.  I cloned it and noticed a helpful place in the source code for it, tested it, and it seems to work good.  The repo referenced this article in its implementation which I copied into that example function above: https://en.wikipedia.org/wiki/Vector_projection

**Comment by bitshifter** [comment]
Hi @TCROC , yeah I think vector projection / rejection are useful things to add.

**Comment by TCROC** [comment]
Looking more into the project function, this would probably make more sense for the function and parameter names:

```
    fn project(self, vector_to_project_onto: Self) -> Self {
        vector_to_project_onto.mul_scalar(self.dot(vector_to_project_onto))     
    }
```

**Comment by bitshifter** [comment]
Generally I try end explain the details in the doc comments, so the variable names aren't too critical. There is the question of if we should require the vector to project onto to be normalized, or if there should be 2 methods, one for normalized vectors and one for vectors of any non-zero length.

**Comment by TCROC** [comment]
I was thinking and reading about it.  I don't think we need to enforce normalization.  That should be up to the user to make sure the vector they are projecting onto is normalized if they want it normalized.  There may be use cases where it makes sense to not normalize.

**Comment by bitshifter** [comment]
For example the implementation from Foundations of Game Engine Development looks like this (C++)

```
inline Vector3D Project(const Vector3D& a, const Vector3D& b)
{
	return (b * (Dot(a, b) / Dot(b, b)));
}
```

which works with any non-zero `b`. If you know your vector is already length 1 then you don't need to do the divide, but this method would be cheaper than requiring a normalized `b` if you don't already have one, since you skip a `sqrt`.

**Comment by TCROC** [comment]
Oh!  Ok I think I see the value in having 2 functions now.  For performance.  So if I understand correctly, if you already have a normalized vector, then you wouldn't have to divide by Dot(b,b)?

If so, I can see an advantage to having ``project`` and ``project_normalized`` functions.

**Comment by TCROC** [comment]
where ``project``, you have to normalized the vector you are passing in yourself **if** you want it normalized.  And in ``project_normalized``, it expects the vector you are passing in to be normalized.

**Comment by bitshifter** [comment]
Yeah, because `b.dot(b)` should be ~1.0. I would probably prefer `project_onto` and `project_onto_normalized` or `project_onto_unit` I guess, because you are projecting `self` onto the input vector so `a.project_onto(b)`.

**Comment by TCROC** [comment]
I agree.  That makes sense.  I like the idea of ``project_onto`` and ``project_onto_normalized``.

**Comment by bitshifter** [comment]
@TCROC were you working on a PR for this? If not I might take a look at it soon.

**Comment by TCROC** [comment]
@bitshifter you are good to work on it 👍.

I was looking into potentially doing a PR, but hit a roadblock when I got to writing the unit test. I'll pay attention to your PR so that I get a better idea of how to contribute in the future.
