### ISSUE TITLE
Add support for WASM intrinsics

### ISSUE THREAD

**Issue by bitshifter** [bitshifter/glam-rs#193]
These are getting stabilized.

I need to work out a nice way of adding tests for WASM. At the moment they're kind of separate to libtest.

**Comment by Ciantic** [comment]
Great library!

Is this issue about [WASM SIMD "intrinsics"](https://v8.dev/features/simd)?

P.S. I'm experimenting with WASM "threading" and glam. Glam is joy to use, using Rust with WASM threading is terrible 😀 though.

**Comment by bitshifter** [comment]
Thanks! Yep, this is about wasm simd intrinsics.

**Comment by bitshifter** [comment]
For testing, this in theory should work but it would be good to come up with something that doesn't require adding this to every test in glam

```
#[cfg_attr(not(target_arch = "wasm32"), test)] 
#[cfg_attr(target_arch = "wasm32", wasm_bindgen_test)]
fn the_test() {}
```
