### ISSUE TITLE
Compilation failed on koji i686

### ISSUE THREAD

**Issue by remilauzier** [bitshifter/glam-rs#203]
https://kojipkgs.fedoraproject.org//work/tasks/5288/70575288/build.log
The compilation passed on the other architectures.

error[E0080]: evaluation of constant value failed
   --> src/macros.rs:21:23
    |
21  |           const _: [(); 0 - !{
    |  _______________________^
22  | |             const ASSERT: bool = $x;
23  | |             ASSERT
24  | |         } as usize] = [];
    | |__________________^ attempt to compute `0_usize - 1_usize`, which would overflow
    | 
   ::: src/affine2.rs:501:5
    |
501 |       const_assert_eq!(8, core::mem::align_of::<super::DAffine2>());
    |       -------------------------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by bitshifter** [comment]
What version of glam are you building? The code looks old, this issue has been fixed on git master but the fix isn't in a crates.io release yet. It will be in 0.17 when that happens.

**Comment by bitshifter** [comment]
In any case, I'll close this since judging by the error message this is fixed in recent versions.

**Comment by remilauzier** [comment]
I was using the latest version on crate.io. i just have to deactivate i686 build until the fix is propagate since fedora don't like pulling from git.

**Comment by bitshifter** [comment]
@remilauzier should be fixed in release 0.17.x
