### ISSUE TITLE
Missing serialization support for Affine2 / DAffine2 / Affine3 / DAffine3

### ISSUE THREAD

**Issue by 0HyperCube** [bitshifter/glam-rs#209]
We're using glam in [Graphite](https://editor.graphite.design), and it would be useful [for this PR](https://github.com/GraphiteEditor/Graphite/pull/220) to have DAffine2 able to be serialized without a proxy. Serde's `Serialize` seems to be implemented for all types except for these 4.

I assume it would be reasonably easy to add these?

**Comment by bitshifter** [comment]
Those types are new so probably I've forgotten to implement a bunch of optional features for them. They are composed from other types which do implement serialisation to it should be easy to add.

**Comment by bitshifter** [comment]
@0HyperCube  These are in release 0.17.1
