### ISSUE TITLE
Test failed on fedora koji

### ISSUE THREAD

**Issue by remilauzier** [bitshifter/glam-rs#213]
https://koji.fedoraproject.org/koji/taskinfo?taskID=71113565

Some test failed when use on other architecture support by fedora. x86_64 is unaffected.
on i686:
---- dvec4::test_align stdout ----
thread 'dvec4::test_align' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `4`', tests/vec4.rs:937:9

on S390x:
---- vec4::test_align stdout ----
thread 'vec4::test_align' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `4`', tests/vec4.rs:839:13

**Comment by bitshifter** [comment]
Ah, I should remove these as I have compile time checks now instead

**Comment by bitshifter** [comment]
I've released 0.17.2 which hopefully fixes these. Unfortunately I don't know how to actually test these platforms to possibly other problems could surface.

**Comment by remilauzier** [comment]
Test work on x86_64 and i686, but failed on others arch.
https://koji.fedoraproject.org/koji/taskinfo?taskID=71954581

**Comment by bitshifter** [comment]
@remilauzier I've committed another fix for this, I found a way to test without access to these platforms using `RUSTFLAGS="-C target-feature=-sse2" cargo test --target i686-pc-windows-msvc` on a windows machine.

Is it possible for you to try running your packaging tests on the git master version of glam before I make another release?

**Comment by remilauzier** [comment]
@bitshifter I've tested your change on fedora copr and everything seem to work. Some arch are emulated on copr, but that shouldn't have change the test result. I will test it on fedora koji when you make a new release.

**Comment by remilauzier** [comment]
https://copr.fedorainfracloud.org/coprs/remilauzier/glam/build/2332284/
S390x seem to have been stuck in a loop when compiling criterion, so we will know only when I can test it on koji.

**Comment by bitshifter** [comment]
Thanks @remilauzier , hopefully it's all working now, I'll make a new release soon.

**Comment by bitshifter** [comment]
@remilauzier I've published 0.17.3, hopefully all the tests pass this time :)

**Comment by remilauzier** [comment]
Everything work!
