### ISSUE TITLE
Upstream face_toward from Bevy

### ISSUE THREAD

**Issue by alice-i-cecile** [bitshifter/glam-rs#214]
As implemented [here](https://github.com/bevyengine/bevy/blob/b1ed28e17e5eaba2426ae447cd80c77e9ed8bb05/crates/bevy_math/src/face_toward.rs), this is a very convenient utility function that other users could benefit from.

Doing so would allow Bevy to deprecate our own implementation and avoid the extension trait.

**Comment by bitshifter** [comment]
As glam intends to be co-ordinate system agnostic it would need to be renamed `face_toward_rh` and a corresponding `face_toward_lh` should also be added. 

Bevy switched from `Mat4::look_at_rh` to `Mat4::face_toward` in this commit https://github.com/bevyengine/bevy/commit/3ee8aa8b0fcd87de885bbd483dde3e8203ba2f21 but it's unclear to me why this change was made? How does this function differ from `Mat4::look_at_rh`? It looks like perhaps `Mat4::face_toward` is the same as `Mat4::look_at_rh().inverse()`? What is the benefit of one over the other for the purpose of documentation and explaining these methods to users?

**Comment by alice-i-cecile** [comment]
Hmm. That's a very good question. I'll ask around.

**Comment by alice-i-cecile** [comment]
Closing, per the discussion in https://github.com/bevyengine/bevy/pull/3503
