### ISSUE TITLE
Implement modulo and remainder operators for numeric vector types

### ISSUE THREAD

**Issue by alice-i-cecile** [bitshifter/glam-rs#218]
This is a convenient and common math feature; we needed it for `UVec2` when handling tile chunks.

Looks like the [Rem trait](https://doc.rust-lang.org/std/ops/trait.Rem.html) is the standard tool for this in Rust, but orphan rules mean that glam must be the implementor.

`rem_euclid` would also be nice to implement for types that have negative values (true modulo is often much more useful than remainder, such as for wrapping logic). See this [Rust RFC](https://github.com/rust-lang/rfcs/blob/master/text/2169-euclidean-modulo.md) for some further motivation.

All of these functions are trivially wrapped from the base numeric types; this is just a request for sugar.

**Comment by bitshifter** [comment]
I've added `Rem` and `RemAssign`. I might wait and see on `rem_euc`. Looking at the RFC `div_euc` and `rem_euc` have been in nightly for a while, but haven't been stabilised yet.
