### ISSUE TITLE
Remove Angle?

### ISSUE THREAD

**Issue by repi** [bitshifter/glam-rs#22]
Have there been any thoughts about keeping or removing the `Angle` type?

I'm a bit conflicted but it feels a bit out of place to have a higher level type wrapper like `Angle` to make radians vs degrees explicit and safe, but at the same time not have a type such as `Point3`.

I'm not proposing to add a `Point3` though and think it is good to just have the core primitive types here.

I do like the explicitness of `Angle::from_radians` but I could just as well see `glam` declaring that all angles are radians (which is how they are stored anyway) and that is how we've have defined inside our engine as well.

So I do have a slight preference to simply not having an `Angle` type, and wanted to start a discussion to see what @bitshifter and everyone else thinks.

**Comment by bitshifter** [comment]
I think it probably does make sense to remove it on balance. A lot of my use of `glam` has involved manually entering angles for various things, those tend to be in degrees so the explicitness has been good. That said, it's not that common to do that usually. Also less code is good.

**Comment by bitshifter** [comment]
Note that everything that did take `Angle` as a parameter now takes `f32` in radians with the exception of perspective matrix creation which expects `fov_y` parameters to be in degrees. Let me know if that's what you'd expect with regards to the `fov_y` parameter.

**Comment by repi** [comment]
Sweet. And yeah the `fov_y` parameter should be in radians as well

**Comment by bitshifter** [comment]
https://github.com/EmbarkStudios/rust-ecosystem/issues/36#issuecomment-531368385 fixed in release 0.8.0.

**Comment by repi** [comment]
Awesome thanks!
