### ISSUE TITLE
Bytemuck feature when targeting SPIRV

### ISSUE THREAD

**Issue by pema99** [bitshifter/glam-rs#229]
Hey, I'm trying to compile a crate which depends on glam with for SPIRV arch with `rust-gpu`. I'm getting the error `error: `bytemuck` feature is not supported when building for SPIR-V.` I'm curious what the reasoning behind this is? And is there any way around this? Bytemuck is `no_std`, so what is the issue?

**Comment by bitshifter** [comment]
You would need to ask the rust-gpu folks. They contributed the spir-v code. I'd recommend trying their discord.

**Comment by pema99** [comment]
I'll try the discord, thanks. For anyone viewing this in the future, `std::slice::from_raw_parts` worked for my use case https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html
