### ISSUE TITLE
New version 0.19?

### ISSUE THREAD

**Issue by bonsairobo** [bitshifter/glam-rs#242]
Just curious if there are plans to cut a version in the near future. I've got a downstream crate that I'd like to publish relatively soon. No rush, really. Just want to get an estimate if you have one.

**Comment by bitshifter** [comment]
Ah yep, probably soon. I have a couple of small things I need to do before
making another release. Hopefully this weekend.

**Comment by bonsairobo** [comment]
Nice, thank you!

**Comment by bitshifter** [comment]
0.19.0 is released!
