### ISSUE TITLE
X Y Z and W Constants for Matrices?

### ISSUE THREAD

**Issue by JonahPlusPlus** [bitshifter/glam-rs#253]
For each matrix could we get constants for x, y, z and w? So for Mat2::X, it would be [[1.0, 0.0], [0.0, 0.0]], essentially IDENTITY, but for split up for each field. I don't know how to implement this myself for a pull request, so I'm hoping someone else does.

I'm coming from Bevy, where I am making a plugin that takes in a Mat2 to determine direction, and X and Y are going to be common, so it would be easier to have constants for them. I figure this would be useful for other projects, so I traveled upstream to here.

**Comment by bitshifter** [comment]
Can you describe how you intend to use these?

**Comment by JonahPlusPlus** [comment]
Say I get a Vec2 for mouse delta and I want to know how much it moved in a certain direction. I could multiply it with `Mat2::X` to get the movement in the X direction or `Mat2::Y` to get the movement in the Y direction. Alternatively, I could set a custom Mat2 to get the movement in a custom axis, say a 45 degree angle. 

Why would anybody want to use a custom angle? For example, someone could use it for an isometric game, where the camera angle doesn't match the actual postions of objects, and moving something along a custom angle moves along a regular axis, but it looks like the custom axis from the camera's perspective.

**Comment by JonahPlusPlus** [comment]
However, X and Y seem like the most common use cases, I just want added flexibility. So, I think adding constants would be good so users don't have to write it all out every time they want a single axis.

**Comment by bitshifter** [comment]
> Say I get a Vec2 for mouse delta and I want to know how much it moved in a certain direction. I could multiply it with Mat2::X to get the movement in the X direction or Mat2::Y to get the movement in the Y direction.

Isn't this the same as accessing x or y in the original vector?

I'm not quite follow your custom axis example, can you provide some sample code of how this would work?

There are a couple of different ways of adding matrix constants in your own code:

```rust
const MAT2X : Mat2 = const_mat2!([1.0, 0.0], [0.0, 0.0]);
```

or via your own trait if you prefer

```rust
trait Mat2Ext {
    const X : Self;
}

impl Mat2Ext for Mat2 {
    const X: Self = const_mat2!([1.0, 0.0], [0.0, 0.0]);
}
```

**Comment by JonahPlusPlus** [comment]
Yeah, I can do that, just thought that maybe other people would like this.

**Comment by bitshifter** [comment]
Because the benefits of these constants are a lot less clear to me than existing constants I think I will close this for now. I was also a bit weary of adding matrix constants that are non-invertible (other than `ZERO` of course), seems like that could catch people out.
