### ISSUE TITLE
Write Documentation Examples

### ISSUE THREAD

**Issue by RpxdYTX** [bitshifter/glam-rs#273]
Most of the functions are kind of confusing, they don't have code examples in the documentation. Also I would like to see some use cases in the function documentation such as "function `x` is recommended to be used when dealing with OpenGL, but function `y` should be used when working with DirectX/Direct3D", those things and advices in the docs would be helpful.

**Comment by bitshifter** [comment]
What specific functions would you like documentation improved on?

**Comment by bitshifter** [comment]
Needs more info.
