### ISSUE TITLE
Add support for `[-1, 1]` depth ranges for orthpgraphic and perspective projection matrices

### ISSUE THREAD

**Issue by RpxdYTX** [bitshifter/glam-rs#274]
Crates like [`vek`](https://crates.io/crates/vek) allows the creation<sup><a href="https://docs.rs/vek/latest/vek/mat/repr_c/column_major/mat4/struct.Mat4.html#method.perspective_lh_no">1</a></sup> of `[-1, 1]` depth ranges, supporting more projection matrix alternatives, making libraries like OpenGL usable.

**Comment by RpxdYTX** [comment]
The `<sup>` link points to the `Mat4::perspective_lh_no` function, but this would apply both to perspective and orthographic, independently on right or left handed matrix.

**Comment by bitshifter** [comment]
glam does have methods for creating gl perspective matrices, providing the same functionality as `gluPerspective` and `glOrtho`. See https://docs.rs/glam/latest/glam/f32/struct.Mat4.html#method.perspective_rh_gl and https://docs.rs/glam/latest/glam/f32/struct.Mat4.html#method.orthographic_rh_gl. Are these sufficient for your use case? Early on I considered gl to be effectively deprecated, so the focus is more on the 0 to 1 depth range options.

**Comment by Calandiel** [comment]
Any reason for perspective_lh_gl not being a thing?

**Comment by bitshifter** [comment]
Mostly because the existing ones are copies of standard gl functions like `gluPerspective` which is right handed. Are you using left handed projections with gl?

**Comment by Calandiel** [comment]
I was, yeah. Mostly for compatibility with some older code
