### ISSUE TITLE
Implement wasm_bindgen ABI traits

### ISSUE THREAD

**Issue by voxelstack** [bitshifter/glam-rs#292]
Would implementing the [wasm_bindgen ABI traits](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen/convert/trait.FromWasmAbi.html?search=WasmAbi) be a relevant PR?

I am willing to give it a go but would probably need a bit of help.

**Comment by bitshifter** [comment]
Hi, there is a bit of discussion around adding support for this here https://github.com/bitshifter/glam-rs/discussions/277 including a suggestion on how it could be approached.

In principle it seems like a potentially useful thing, so I am open to adding it. However I'd like some way of automatically testing it to be included with any PR as this is something that's pretty unfamiliar to me, I don't what to inadvertently break it further down the track.

At the moment I'm doing an experimental refactor of glams internals, which would conflict with any changes like this. That wouldn't prevent it from being worked on, I might just not be able to merge it until after I've finished (or abandoned) this refactor.

Closing this for now in favour of continuing discussions here https://github.com/bitshifter/glam-rs/discussions/277.
