### ISSUE TITLE
Add negative axes for vectors

### ISSUE THREAD

**Issue by 00sos00** [bitshifter/glam-rs#295]
Not sure if this is worth it but shouldn't we have these?

`Vec2::NEG_X`
`Vec2::NEG_Y`

`Vec3::NEG_X`
`Vec3::NEG_Y`
`Vec3::NEG_Z`

`Vec4::NEG_X`
`Vec4::NEG_Y`
`Vec4::NEG_Z`
`Vec4::NEG_W`

or maybe
```rs
impl Vec {
    const fn neg(self) -> Self {
        vec(-self.x, -self.y, ...)
    }
}

impl Neg for Vec {
    const fn neg(self) -> Self {
        self.neg()
    }
}
```

**Comment by bitshifter** [comment]
yeah I think NEG constants are reasonable.
