### ISSUE TITLE
`Mat3::from_mat4` documentation slightly misleading

### ISSUE THREAD

**Issue by cwfitzgerald** [bitshifter/glam-rs#316]
> Creates a 3x3 matrix from a 4x4 matrix, discarding the 3rd row and column.

The documentation from `from_mat4` suggests that it keeps the 1st, 2nd, and 4th column, but the actual code keeps the 1st, 2nd, and 3rd. I'm not sure which is the intended behavior, but as it stands it's not clear.

**Comment by bitshifter** [comment]
Good point, I'm counting for zero there which is probably a bit confusing :)
