### ISSUE TITLE
Implement Sum for Vec3 and other vector types

### ISSUE THREAD

**Issue by paul-hansen** [bitshifter/glam-rs#326]
The [Sum trait](https://doc.rust-lang.org/std/iter/trait.Sum.html) can't be automatically derived from Add as the Sum trait in rust allows for the return type to be different. This means we need to implement it ourselves if we want to be able to do things like:
``` rust
let translations: Vec<Vec3> = transforms.iter().map(|t| t.translation()).collect();
let total: Vec3 = translations.iter().sum();  // <-- adds them all together
let average: Vec3 = total / translations.len() as f32;
```

I think normally implementations for this should be as simple as:
``` rust
impl Sum<Vec3> for Vec3 {
    fn sum<I: Iterator<Item = Vec3>>(iter: I) -> Self {
        iter.fold(Vec3::ZERO, |a, b| a + b)
    }
}
```

Is this something we want? Anything I should be aware of before working on a PR for this?

**Comment by bitshifter** [comment]
There is a sum impl on all vector types, https://docs.rs/glam/latest/src/glam/f32/vec3.rs.html#1006-1014

Or are you meaning something different?

**Comment by paul-hansen** [comment]
Oof you are right, I think I just needed references to make it work. I thought I looked at the docs to see if it was implemented too, I missed it somehow. Thanks, and sorry for wasting your time!

**Comment by bitshifter** [comment]
Perhaps there should be a non reference version, usually glam doesn't use references because everything is copy

**Comment by paul-hansen** [comment]
Hmm, I haven't really looked into it before but it does seem like something the standard library does for copy types:
Duration: https://doc.rust-lang.org/src/core/time.rs.html#1016-1028
f32: https://doc.rust-lang.org/std/primitive.f32.html#impl-Sum%3C%26%27a%20f32%3E

**Comment by bitshifter** [comment]
Re-opening this is the lack of a by-value implementation came up again recently.

**Comment by paul-hansen** [comment]
Looks like it's already in main now, was added in: https://github.com/bitshifter/glam-rs/pull/333 (Correct me if I'm wrong though)
Thanks @nekodjin !
