### ISSUE TITLE
Vec3 ignores 'scalar-math' feature

### ISSUE THREAD

**Issue by curldivergence** [bitshifter/glam-rs#332]
Hi! I've been using `glam` for my toy DX12 renderer, and have stumbled upon a weird thing - why `Vec3` has `repr(simd)` even with `scalar-math` feature enabled? I'd expect it to have `repr(C)` layout with this feature enabled, otherwise it leads to inconsistencies in Rust/HLSL constant buffer layouts. Thank you!

**Comment by bitshifter** [comment]
I don't think that is true. The struct definition is here - https://github.com/bitshifter/glam-rs/blob/main/src/f32/vec3.rs#L20-L28

```rust
/// A 3-dimensional vector.
#[derive(Clone, Copy, PartialEq)]
#[cfg_attr(not(target_arch = "spirv"), repr(C))]
#[cfg_attr(target_arch = "spirv", repr(simd))]
pub struct Vec3 {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}
```

So `repr(simd)` is only used if the target is `spriv`, otherwise it's `repr(C)`. So only `rust-gpu` `spirv` targets should be using `repr(simd)`.

**Comment by curldivergence** [comment]
Hm, you're right, I misread the attributes, so it must be something else. Sorry for bothering :)
