### ISSUE TITLE
Add Sum<Self> and Product<Self> to the test suite

### ISSUE THREAD

**Issue by nekodjin** [bitshifter/glam-rs#334]
This addition is due to PR #333. Self-explanatory. Submitting this issue to remind myself to do it later.

**Comment by bitshifter** [comment]
example of test for non-reference trait impl

```rust
assert_eq!(vec![Vec2::ONE, Vec2::ONE].into_iter().sum::<Vec2>(), Vec2::ONE + Vec2::ONE);
```
