### ISSUE TITLE
Dot product does not use SSE4.1 _mm_dp_ps

### ISSUE THREAD

**Issue by rodolphito** [bitshifter/glam-rs#338]
The following functions could use the `_mm_dp_ps` instruction which was [stabilized in rust 1.27](https://doc.rust-lang.org/stable/core/arch/x86_64/fn._mm_dp_ps.html):
`dot4_into_m128` and `dot3_into_m128` in `sse2.rs`
`dot4_into_f32x4` and `dot3_into_f32x4` in `coresimd.rs`

Additionally, a vector-valued dot method should be exposed on Vec4 and Vec3A that returns the result in all channels.

**Comment by bitshifter** [comment]
Generally I've stuck with SSE2 as the lowest common denominator on x86. If I was to add SSE4.1 support it's probably worth going over all of the SSE2 code in glam, not just dot product. It would require an extra build on CI to ensure it's tested.

**Comment by rodolphito** [comment]
I see. [Steam hardware survey](https://store.steampowered.com/hwsurvey) reports 99% adoption for SSE 4.1 (visible in 'Other settings' collapsed menu at the bottom). I think it would be worth it to support SSE 4.1. How can I help make this happen?

**Comment by bitshifter** [comment]
Just checking on my machine (AMD TR 3990X), the dedicated SSE4.1 instruction was 40% slower than the SSE2 implementation for a 3D dot product. It might be worth checking that before going to far with this.

To test I changed `src/sse2.rs` to:

```rust
#[cfg(not(target_feature = "sse4.1"))]
#[inline(always)]
pub(crate) unsafe fn dot3_in_x(lhs: __m128, rhs: __m128) -> __m128 {
    let x2_y2_z2_w2 = _mm_mul_ps(lhs, rhs);
    let y2_0_0_0 = _mm_shuffle_ps(x2_y2_z2_w2, x2_y2_z2_w2, 0b00_00_00_01);
    let z2_0_0_0 = _mm_shuffle_ps(x2_y2_z2_w2, x2_y2_z2_w2, 0b00_00_00_10);
    let x2y2_0_0_0 = _mm_add_ss(x2_y2_z2_w2, y2_0_0_0);
    _mm_add_ss(x2y2_0_0_0, z2_0_0_0)
}
#[cfg(target_feature = "sse4.1")]
#[inline(always)]
pub(crate) unsafe fn dot3_in_x(lhs: __m128, rhs: __m128) -> __m128 {
    _mm_dp_ps(lhs, rhs, 0x71)
}
```

I used a bench I'd added earlier that uses dot product in `benches/vec3a.rs`:

```rust
bench_binop!(
    vec3a_distance_squared,
    "vec3a distance_squared",
    op => distance_squared,
    from1 => random_vec3a,
    from2 => random_vec3a
);
```

then bench

```sh
cargo bench "vec3a distance_squared"
```

versus

```sh
RUSTFLAGS='-C target-feature=+sse4.1' cargo bench "vec3a distance_squared"
```

**Comment by aloucks** [comment]
> Just checking on my machine (AMD TR 3990X), the dedicated SSE4.1 instruction was 40% slower than the SSE2 implementation for a 3D dot product. 

FWIW, I've observed similar results in the past with the sse4 dot product instruction being slower in many cases (on an intel core i9-9900k). I also vaguely remember reading stackoverflow posts where other people were also reporting it being outperformed by sse2 techniques.

**Comment by bitshifter** [comment]
I suspect it exists for convenience rather than performance. Horizontal dot product doesn't play to SIMD's strengths.

**Comment by bitshifter** [comment]
For other SSE2 vs SSE4.1 instructions, even things like `_mm_permute_ps` instead of `_mm_shuffle_ps` don't look like they are any faster, often slower on AMD according to https://www.agner.org/optimize/instruction_tables.pdf. 

SSE2 is a good base, it's enabled by default on x86_64 builds so I will always keep it. Adding SSE4.1 will just mean more test permutations, so unless there is a clear benefit over SSE2 for some functionality I'd rather not add support for it.

The other request of returning the result of a dot product in a vector I can do, obviously I use this internally so it makes sense that users might find it useful.

**Comment by rodolphito** [comment]
Thanks for the easy instructions! I ran the benchmarks, same result on my 11th gen intel i7. SSE 4.1 _mm_dp_ps is indeed 40% slower than the SSE 2 implementation. I also had an associate test on PS5, SSE 4.1 is only 20% slower there. I suspect that the slowness might be due to slightly different rounding semantics, it might be an FMA style instruction that defers floating point round-off until after all the adds. I've seen FMA be slower than separate mul + add.

I've made a pull request adding the API surface plus tests, keeping the SSE 2 implementation. I'll benchmark any future potential alternate SSE 4.1 implementations I'm curious about.

**Comment by rodolphito** [comment]
For posterity, another failed experiment:

SSE2  (-73.553% runtime compared to SSE4.1)
```rust
    #[inline]
    pub fn mul_transposed_vec3a(&self, rhs: Vec3A) -> Vec3A {
        self.transpose().mul_vec3a(rhs)
    }
```

SSE4.1  (+277.66% runtime compared to SSE2)
```rust
    #[inline]
    pub fn mul_transposed_vec3a(&self, rhs: Vec3A) -> Vec3A {
        unsafe {
            let x = _mm_dp_ps(self.x_axis.0, rhs.0, 0x7f);
            let y = _mm_dp_ps(self.y_axis.0, rhs.0, 0x7f);
            let xy = _mm_blend_ps(x, y, 0b0010);
            let z = _mm_dp_ps(self.z_axis.0, rhs.0, 0x7f);
            let xyzz = _mm_blend_ps(xy, z, 0b1100);
            Vec3A(xyzz)
        }
    }
```

Basically, don't do this, it sucks lol
