### ISSUE TITLE
Add const to from_diagonal

### ISSUE THREAD

**Issue by VirxEC** [bitshifter/glam-rs#339]
The function -> https://docs.rs/glam/0.21.3/glam/f32/struct.Mat3A.html#method.from_diagonal
Looking at the code, there's no real reason why this function can't be a `const fn`. Can this please be changed?

Also, it looks like `to_cols_array_2d` can also easily be a `const fn`.

**Comment by VirxEC** [comment]
I'll make a pr then

**Comment by bitshifter** [comment]
Thanks for the PR!
