### ISSUE TITLE
Impl Hash for Vec2?

### ISSUE THREAD

**Issue by jameslinimk** [bitshifter/glam-rs#367]
I know `UVec` and `IVec` already have Hash derived, so why doesn't `Vec2`?

**Comment by cwfitzgerald** [comment]
Floats do not impl hash because they don't obey the requirement of `hash(n1) != hash(n2) => n1 != n2`. If both n1 and n2 are NaN, then `hash(n1) == hash(n2)` is true, but `n1 != n2`.

**Comment by bitshifter** [comment]
Primarily this isn't supported in glam because hashing of `f32` and `f64` is not natively supported in Rust. See https://github.com/bitshifter/glam-rs/issues/123 for more detailed discussion.
