### ISSUE TITLE
Why no {distance,length}_squared for {I,U}Vec{2,3,4} ?

### ISSUE THREAD

**Issue by Des-Nerger** [bitshifter/glam-rs#381]
I see no reason for the integer vectors to not have the `distance_squared` and `length_squared` methods, like the rest of the numeric vectors have. Is there any?

**Comment by bitshifter** [comment]
A few reasons. 

It is unclear to me what users would expect an integer length function to do with respect to rounding, potentially that answer  depends on their use case. Also there is no i32 or u32 implementation of `sqrt` in the Rust standard library, so any integer length function would need to cast to float anyway. I think it would preferable for users to solve for their own use case here, if they need a length then they can use `as_vec3().sqrt().{ceil(),round()}.as_ivec3()`. Providing all possibly permutations here as part of the glam interface doesn't seem worthwhile to me.

`length_squared` on the other hand could be provided without needing to worry about `sqrt`, but then that's just shorthand for `x.dot(x)`.

What is your case for needing this?

**Comment by bitshifter** [comment]
I see I failed at reading comprehension, distance / length squared should be fine.

**Comment by Des-Nerger** [comment]
> but then that's just shorthand for x.dot(x)

Yeah, but If `x` is not an identifier but a (possibly long) expression, then in case of using `().dot()` we would have to reduplicate those code / calculations.

> What is your case for needing this?

Calculating (squared) distances of two dimensional array indices:
```rust
for neighbor in neighbors.iter().filter_map(|&(i, neighbor)| {
    const PIXELCENTER_MUL_2: i32 = 1;
    ((i * 4 - j * 2 + PIXELCENTER_MUL_2).length_squared() <= IVec2::new(3, 1).length_squared())
        .then_some(neighbor)
}) {...}
```
https://github.com/Des-Nerger/d2sw_tiled_project/blob/b85fcee/src/bin/waifu2xPNG-originalIndexedPNG_into_fixedWaifu2xPNG.rs#L66

and of RGBA colors:
```rust
let squared_distance = (rgba
    - IVec4::from((
        IVec3::from_array(
            unsafe {
                <[u8; RGB_SIZE]>::try_from(&png_pal[neighbor * RGB_SIZE..][..RGB_SIZE]).unwrap_unchecked()
            }
            .map(|color_component| color_component as _),
        ),
        (if neighbor == FULLY_TRANSPARENT as _ { u8::MIN } else { u8::MAX }) as _,
    )))
.length_squared();
```
https://github.com/Des-Nerger/d2sw_tiled_project/blob/b85fcee/src/bin/waifu2xPNG-originalIndexedPNG_into_fixedWaifu2xPNG.rs#L71
