### ISSUE TITLE
Add `From` trait implementation to create Vec2 Vec3 and Vec4 from arrays.

### ISSUE THREAD

**Issue by MalekiRe** [bitshifter/glam-rs#386]
In mint you can do the following: 
```
let foo: Vector3<f32> = [0.0, 1.0, 2.0].into();
```
This makes the usage of mint types far cleaner than the 
```
Vec3::new(0.0, 1.0, 2.0)
```
That we are used to.
Thoughts on adding the ability to create Vectors from arrays like Mint?

This also makes the usage of glam types in APIs cleaner to use, as now this is doable.

```
fn foo(bar: impl Into<Vec3>) {
    let bar =  bar.into();
    //.. do stuff with bar
}

foo([0.0, 1.0, -3.4]);
```
vs
```
foo(Vec3::new(0.0, 1.0, -3.4));
```

**Comment by bitshifter** [comment]
There are from array implementations for most types in glam already https://docs.rs/glam/0.23.0/src/glam/f32/vec3.rs.html#1128-1133

**Comment by bitshifter** [comment]
From array is already implemented and this currently works in `glam`:

```rust
fn foo(bar: impl Into<Vec3>) {
    let bar =  bar.into();
    dbg!(bar);
}

foo([0.0, 1.0, -3.4]);
```
