### ISSUE TITLE
Truncating a vector

### ISSUE THREAD

**Issue by feliwir** [bitshifter/glam-rs#397]
Hello,

how do i truncate (= calling `truncf` on each element)  a Vec3 in glam? The correct `truncate()`  function just removes a element, which is not what i want. 

The behaviour i'm looking for is like this:
https://github.com/jansol/texpresso/blob/main/lib/src/math/vec3.rs#L75

**Comment by bitshifter** [comment]
Ah right, surprisingly I have never come across this function before! Seems reasonable to add it. It's a shame I didn't know about it or I might have called `truncate` something else.

The Rust function is https://doc.rust-lang.org/std/primitive.f32.html#method.trunc.

**Comment by feliwir** [comment]
Could we use the intrinsic `_mm_round_ss` with rounding mode truncation?
