### ISSUE TITLE
I wish I could try_into between glam types

### ISSUE THREAD

**Issue by mcclure** [bitshifter/glam-rs#401]
I have two u32s. I want to put them in an IVec2. I run:

`let size= IVec2::new(width.try_into().unwrap(), height.try_into().unwrap());`

That's a little wordy. Wait, I think. I could do the try_into on the vector:

`let size:IVec2 = UVec2::new(config.width, config.height).try_into().unwrap();`

That feels cleaner! But it's not allowed:

```
   --> src/main.rs:149:82
    |
149 |                         let size:IVec2 = UVec2::new(config.width, config.height).try_into().unwrap();
    |                                                                                  ^^^^^^^^ the trait `From<UVec2>`
is not implemented for `IVec2`
    |
    = help: the following other types implement trait `From<T>`:
              <IVec2 as From<(i32, i32)>>
              <IVec2 as From<[i32; 2]>>
    = note: required for `UVec2` to implement `Into<IVec2>`"0.24.0"
    = note: required for `IVec2` to implement `TryFrom<UVec2>`
    = note: required for `UVec2` to implement `TryInto<IVec2>`
```

Is it possible for try_into between glam types to work? I see there's as_uvec and as_ivec but those are unconditional conversions (IE they will misbehave if `1<<31` somehow winds up in the uvec).

#### Configuration

Rust 1.69.0, Glam 0.24.0

**Comment by bitshifter** [comment]
Seems that there is some demand for this. Closing this one as a dup of #336.

**Comment by bitshifter** [comment]
This has been implemented and is in main now.
