### ISSUE TITLE
Add `must_use` to many methods and functions

### ISSUE THREAD

**Issue by sanbox-irl** [bitshifter/glam-rs#445]
Hello! I'm not very familiar with how we generate code in glam, otherwise i'd love to propose this (if it's simple enough to point me to the start of the trailhead, I'd make a go of this).

There many functions which return a new type rather than mutating the existing type: for example, `Vec2::clamp`. I'd like these to be decorated with `must_use`, which nicely keeps glam inline with how the std handles functions.

What do you think?

**Comment by bitshifter** [comment]
Yeah that's probably sensible. I know I've put it in a few places where it might not be obvious that a method returns something, but not across the board.

**Comment by bitshifter** [comment]
@sanbox-irl I missed the other part of your question. For this change it would be pretty straight forward to do, there are instructions on running the code generator here if you are interested in giving it a go https://github.com/bitshifter/glam-rs/blob/main/codegen/README.md#running-codegen.

**Comment by sanbox-irl** [comment]
Added #449 !

**Comment by sanbox-irl** [comment]
close this as PR was merged!
