### ISSUE TITLE
`Mat4::inverse()` has different result with SSE and scalar version

### ISSUE THREAD

**Issue by SlimeYummy** [bitshifter/glam-rs#468]
I encountered this problem while doing cross-platform deterministic testing for my library. Initially, I found that the results of Mat4::inverse() on x86_64 and aarch64 are different. The cause of this problem is that on x86_64 glam will use the SSE version implementation by default, which is subtly different from the scalar version of the implementation.

Below is my test data:
```rust
Mat4::from_cols(
    Vec4::new(0.1331019, 0.98764026, 0.082769506, 0.0),
    Vec4::new(-0.15312907, -0.062017117, 0.98625845, 0.0),
    Vec4::new(0.97920156, -0.14394742, 0.1429817, 0.0),
    Vec4::new(0.09259742, 1.3122104, -0.010967175, 1.0),
).inverse()

// Scalar version result:
// Mat4 {
//    x_axis: Vec4(0.13310201, -0.15312888, 0.9792013, -0.0),
//    y_axis: Vec4(0.9876401, -0.06201687, -0.14394724, 0.0),
//    z_axis: Vec4(0.08276977, 0.9862582, 0.14298178, -0.0),
//    w_axis: Vec4(-1.3074088, 0.106375, 0.09978565, 1.0)
// }

// SSE version result:
// Mat4 {
//    x_axis: Vec4(0.133102, -0.15312886, 0.9792012, -0.0),
//    y_axis: Vec4(0.98763996, -0.062016863, -0.14394721, 0.0),
//    z_axis: Vec4(0.08276976, 0.9862581, 0.14298175, -0.0),
//    w_axis: Vec4(-1.3074087, 0.10637499, 0.09978564, 0.9999999)
// }
```
This causes that the default features cannot guarantee cross-platform determinism, and users need to manually enable the scalar-math feature.

**Comment by bitshifter** [comment]
This is expected. I'd also recommend enabling the libm feature for determinism.

**Comment by SlimeYummy** [comment]
Thanks for you response.
A little problem for me is that scalar-math feature will disable 16 bit alignment. So I will try portable simd version.

**Comment by bitshifter** [comment]
Which types are you depending on 16 byte alignment for?

**Comment by SlimeYummy** [comment]
Vev4 and Mat4.
Because I need to pass the calculation of glam to other functions using SIMD, 16-bit alignment can reduce some copying.

**Comment by SlimeYummy** [comment]
My current tests show that portable simd works well. Nightly rust is not a problem for me, I also use portable simd in my own code.
