### ISSUE TITLE
Supporting simpler BVecN operations

### ISSUE THREAD

**Issue by sanbox-irl** [bitshifter/glam-rs#474]
Hiya:

```rs
    if movement_amount.x == 0.0 {
        velocity.x = 0.0;
    }
    if movement_amount.y == 0.0 {
        velocity.y = 0.0;
    }
```

I'd love to write:

```
    *velocity *= movement_amount.cmpeq(Vec2::ZERO).as_vec2();
```
but cannot since BVec2 doesn't have an `as_vec2`

Is there another way to make this simpler? I try to keep my vec2 ops applying to both components at the same time

**Comment by bitshifter** [comment]
Hi, for now I think you could write this as:
```
*velocity = Vec2::select(movement_amount.cmpeq(Vec2::ZERO), Vec2::ZERO, velocity);
```

The `as_*` methods typically only support casting between types that native Rust supports, `bool as f32` is not supported in Rust, it suggests going via an integer first, no idea why. However `f32::from(bool)` is supported so perhaps it would be better to add `Vec2::from(BVec2)` to give an easy option to create a vector from a mask.

```
*velocity *= Vec2::from(movement_amount.cmpne(Vec2::ZERO))
```
