### ISSUE TITLE
Implement missing `From<Quat>` for matrices (get basis from quaternion)

### ISSUE THREAD

**Issue by Wilker-uwu** [bitshifter/glam-rs#478]
## What problem does this solve or what need does it fill?

Gathering a Basis (a 3x3 matrix describing various axis rotations of an object) from a Quaternion, useful for more descriptions of the rotation of the object. for instance, the negative Z column of the Basis describes the forward-facing orientation of an object relative to its own rotation as a normalized vector.

## What solution would you like?

Solutions for [3x3 matrix conversions](https://docs.rs/glam/latest/glam/f32/struct.Mat3.html#method.from_quat "Mat3::from_quat") and [4x4 matrix conversions](https://docs.rs/glam/latest/glam/f32/struct.Mat4.html#method.from_quat "Mat4::from_quat") as well as conversions back into quaternions [here](https://docs.rs/glam/latest/glam/f32/struct.Quat.html#method.from_mat3 "Quat::from_mat3") and [here](https://docs.rs/glam/latest/glam/f32/struct.Quat.html#method.from_mat4 "Mat4::from_quat") are already present in Bevy. since there is no disambiguation required for this kind of conversion, the trait implementation could just be an alias for the existing methods.

## What alternative(s) have you considered?

Calling the methods directly. it works and it's readable, just inconvenient, although i'm not sure if `Mat3::from_quat(the_quat.inverse()).axis_z * speed` is better than `(the_quat.inverse() as Mat3).axis_z * some_velocity_vector` for describing some changes i need since that would require me to convert it twice if i need to use the original quaternion as a matrix elsewhere, but that is a different topic i think. 

## Additional context

This is a 1-to-1 copy from the Bevy issue i wrote (see [#12191](/bevyengine/bevy/issues/12191)) where someone pointed me here. i just skimmed over the docs to make sure the links are correct with these docs,.

**Comment by bitshifter** [comment]
Just to be clear, implementing `From` does not allow you to use the `as` keyword. You will still need to use `from` or `into`, e.g.:

```
Mat3::from(the_quat.inverse()).axis_z * some_velocity_vector
```

In this example I think the type would need to be specified, I don't think it could be inferred, e.g. `the_quat.inverse().into().axis_z` probably wouldn't work.

**Comment by Wilker-uwu** [comment]
makes sense, i forgot the `as` keyword is only valid between primitives x.x

**Comment by bitshifter** [comment]
I think a `From<Quat>` does not meet the guidelines for the `From` trait (see https://doc.rust-lang.org/std/convert/trait.From.html#when-to-implement-from):

> The conversion is infallible: if the conversion can fail, use [TryFrom](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) instead; don’t provide a From impl that panics.

The current `Mat3::from_quat` implementation is fallible, it requires the quaternion to be normalized, if glam asserts are enabled it will panic if the quat is not normalized.

>    The conversion is lossless: semantically, it should not lose or discard information. For example, i32: From<u16> exists, where the original value can be recovered using u16: TryFrom<i32>. And String: From<&str> exists, where you can get something equivalent to the original value via Deref. But From cannot be used to convert from u32 to u16, since that cannot succeed in a lossless way. (There’s some wiggle room here for information not considered semantically relevant. For example, Box<[T]>: From<Vec<T>> exists even though it might not preserve capacity, like how two vectors can be equal despite differing capacities.)

While no information is discarded, due to all the floating point math involved if you convert from a quat to a mat3 and back again I don't think you will get exactly the same quat.

>    The conversion is obvious: it’s the only reasonable conversion between the two types. Otherwise it’s better to have it be a named method or constructor, like how [str::as_bytes](https://doc.rust-lang.org/std/primitive.str.html#method.as_bytes) is a method and how integers have methods like [u32::from_ne_bytes](https://doc.rust-lang.org/std/primitive.u32.html#method.from_ne_bytes), [u32::from_le_bytes](https://doc.rust-lang.org/std/primitive.u32.html#method.from_le_bytes), and [u32::from_be_bytes](https://doc.rust-lang.org/std/primitive.u32.html#method.from_be_bytes), none of which are From implementations. Whereas there’s only one reasonable way to wrap an [Ipv6Addr](https://doc.rust-lang.org/std/net/struct.Ipv6Addr.html) into an [IpAddr](https://doc.rust-lang.org/std/net/enum.IpAddr.html), thus IpAddr: From<Ipv6Addr> exists.

Again I feel that there is not a clear case for `From` (or `TryFrom`) in this instance. `From` implementations in glam tend to take values and assign them losslessly into a new type, there's no transformation of data involved, only simple assignment or in some cases conversions that Rust supports itself (e.g. `impl From<bool> for {f32|f64}`.

I think for these reasons I don't think added `From<Quat>` or `TryFrom<Quat>` for `Mat3` would be appropriate.
