### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by Lokathor** [bitshifter/glam-rs#5]
You mention in the readme that you'd like to have no_std support, what are the current blockers?

**Comment by bitshifter** [comment]
https://github.com/rust-lang/rfcs/issues/2505 is the blocker. I had a look at what nalgebra did, which was to let you link your own math functions. I'm not sure if that's the best approach (i.e. I really have no idea), I wasn't keen to just do what nalgebra did without knowing if it was actually a good solution. Potentially glam could just define it's own trig an sqrt functions. That would be an alternative approach to being no_std.

**Comment by Lokathor** [comment]
oh, right. I've spent the past few days safe wrapping sse/sse2 for my core only crate and somehow i still totally forgot that there's no sqrt in core itself.

I'll look in to pure rust sqrt/sin/cos soon and if I find anything promising I'll bring it here too.

**Comment by bitshifter** [comment]
Fixed by #88
