### ISSUE TITLE
Possible Incompleteness

### ISSUE THREAD

**Issue by YichiZhang0613** [bitshifter/glam-rs#501]
In glam-rs/src/u64/u64vec2.rs, the comment indicates that slice must be greater or equal than 2 elements long, while the code doesn't use assert! to check it. There are many similar problems in other functions.
```rust
    /// # Panics
    ///
    /// Panics if `slice` is less than 2 elements long.
    #[inline]
    #[must_use]
    pub const fn from_slice(slice: &[u64]) -> Self {
        Self::new(slice[0], slice[1])
    }
```

**Comment by bitshifter** [comment]
The slice itself asserts that the index is in bounds, so if glam did it as well here it would be checked twice.

See https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=25155bd0f0bc27cb44867d916ce5613c
