### ISSUE TITLE
Quat::from_euler truncates rotations to a single rotation

### ISSUE THREAD

**Issue by ethereumdegen** [bitshifter/glam-rs#503]
Quat::from_euler truncates rotations to a single rotation

I need a function that is similar that DOES NOT truncate rotations to a single rotation but maintains all rotations. Please make one like this - i do not see available in bevy docs (which uses glam)

**Comment by bitshifter** [comment]
Could you provide an example of what you are trying to do?

**Comment by bitshifter** [comment]
Closing without additional info, however I'm assuming that this is about having euler angles greater than 2pi radians resulting in a quaternion that is modulo 2pi radians (e.g. a euler rotation of pi radians is the same as 3pi radians in the resulting quaternion). This is the nature of unit quaternions, they represent a rotation around an axis, the "number of rotations" from euler angles will be lost.
