### ISSUE TITLE
IVec2 and similar types should be Ord.

### ISSUE THREAD

**Issue by mintlu8** [bitshifter/glam-rs#508]
So they can be put in a priority queue and work without a wrapper type.

**Comment by bitshifter** [comment]
A long time ago glam used to implement `PartialOrd` on float vectors (this was before glam had `IVec*`) but it confused users and people asked for them to be removed (#138 , #168) , which they were.

I think the same reasons that people didn't like `PartialOrd` on `Vec*` would apply to `Ord` on `IVec*` as well, so I'm inclined to not add them back.
