### ISSUE TITLE
Make `Vec3A::from_vec4` const

### ISSUE THREAD

**Issue by herabit** [bitshifter/glam-rs#545]
All of the implementations of `Vec3A::from_vec4` do not seem to require non-const functionality, so marking them all as `const fn` will increase their versatility for API consumers.

I would make a pull request if I was more familiar with contributing to open source, as this seems like a minor change, though yeah I'd need to look into how to, do that.

**Comment by herabit** [comment]
Wish I had read the contributing guide, I'll make this into a discussion. I'll leave this open for now just in case this is the preferred channel for communication. Close this if it you desire as, yeah I will create the discussion.

**Comment by bitshifter** [comment]
If it's any consolation almost no one reads the contributing guide :) I really need to make an issue template directing people to discussions.  I replied to your discussion thread but I'll leave this open until the PR is merged.

**Comment by bitshifter** [comment]
It turns out this is not currently possible because Vec3::from_vec4 invokes deref to access the x,y & z values which can't be done in a const context.

At some point this might be possible https://github.com/rust-lang/rust/issues/67792.
