### ISSUE TITLE
Document that serde impls expect a sequence, or support deserializing from map

### ISSUE THREAD

**Issue by Themayu** [bitshifter/glam-rs#555]
This is one of two very closely related issues with this crate as it stands. The other is at #556.

There's no mention in the documentation of the fact that the `serde::Deserialize` implementations on this crate's vector types expect a sequence and don't accept deserializing from a map. This runs contrary to the intuitive expectation, which is that a struct with named fields would support deserializing from a map with those fields named. This wouldn't be as painful as it is were it not also for the problem outlined in #556, which is closely related to this.

To resolve this issue, either the documentation should be adjusted to mention that the structs must be deserialized from a sequence, not a map; or, `visit_map` should be implemented for the structs' visitors so that `deserialize_struct` can be used as a fallback for if `deserialize_tuple_struct` (`visit_seq`) fails to return a value. Whichever happens here is up to you.

**Comment by bitshifter** [comment]
Could you provide steps to reproduce this problem?
