### ISSUE TITLE
Vector type visitors give an incorrect and useless message in their `Visitor::expecting` impls

### ISSUE THREAD

**Issue by Themayu** [bitshifter/glam-rs#556]
This is one of two very closely related issues with this crate as it stands. The other is at #555.

The messages given by the `Visitor::expecting` implementations on this crate's vector type visitors, used in their `Deserialize` impls, is incorrect, as it just says `"struct <type name>"` which gives no helpful details in the error message produced when deserialization fails. This exacerbates the problem caused by #555, as it means there is no way to discover the user's error without reading the crate's source code.

To resolve this issue, [the documentation for `Visitor::expecting`](https://docs.rs/serde/latest/serde/de/trait.Visitor.html#tymethod.expecting) states that it should be used to specify what format the visitor's _input_ is expected to be. You are only providing the name of the _output_ type, which results in an entirely unhelpful error message of, for example:
```
invalid type: map, expected struct Vec2
```
This is incorrect. A proper `expecting` implementation would state that it is expecting a sequence of at least `n` numbers.

**Comment by bitshifter** [comment]
Fixed in #558
