### ISSUE TITLE
Add support for `rand`'s uniform distribution, when using the `rand` feature

### ISSUE THREAD

**Issue by LikeLakers2** [bitshifter/glam-rs#579]
Hi! I'm practicing making games with `bevy`, and I'm making a simple snake game to do so. During this, I was searching for a way to point to a random tile within a grid.

I figured out that `glam` has the `rand` feature - but this only adds support for using `glam` types with the [`Standard` distribution](https://docs.rs/rand/0.8.5/rand/distributions/struct.Standard.html).

Since I had a limited grid size, I wanted to put bounds on the random numbers. This is possible using the `%` operator, but wouldn't necessarily result in a uniform distribution - some numbers may be ever so slightly more likely to appear than others.

I found that `rand` has a [distribution called `Uniform`](https://docs.rs/rand/0.8.5/rand/distributions/struct.Uniform.html), which is exactly what I want - I give it the bounds I want, and it generates a number between those two bounds, without the bias towards certain numbers.

Unfortunately, it seems `glam` doesn't implement the traits needed to use types like `UVec2` with the `Uniform` distribution. I'm making this request in hopes to rectify this issue.

----

**P.S.** Normally, I would be willing to make a PR for this sort of thing. However, I'm hesitant to say that I could deliver correct results for matrices or affine transformations; and for quaternions, I don't even know where to start. That said, if you're okay with a PR that only implements this for the Vec types, I can do that!

**Comment by bitshifter** [comment]
I would be OK with a PR. I added the original rand support to produce data for running benchmarks on and wasn't too concerned with correctness, it turned out that the way I had implemented random quats was not correct distribution wise.

I think it would be OK to only support vectors for now, it can be expanded later if there's a demand. My main request is that you add tests to confirm they're working as expected.

**Comment by LikeLakers2** [comment]
Gotcha - and of course, adding tests isn't a problem.

The only thing I'll say about adding tests, is that I don't know how to test all the properties of the uniform distribution - or if I even should, since I'll most likely just have the implementations wrap around existing `rand` implementations (which are already tested for correctness).

**Comment by LikeLakers2** [comment]
Gotcha - and of course, adding tests isn't a problem.

I will work on the PR soon.
