### ISSUE TITLE
glam won't build because of sse2, but im on x86_64?

### ISSUE THREAD

**Issue by ToastyMod** [bitshifter/glam-rs#58]
I'm trying to build glam alongside glium in a project, the code compiles and runs completely fine on my other computer but on my laptop it's giving me this error:

`error[E0599]: no method named `map_or` found for type `std::result::Result<std::string::String, std:
:env::VarError>` in the current scope
 --> C:\Users\anumr\.cargo\registry\src\github.com-1ecc6299db9ec823\glam-0.8.7\build.rs:8:10
  |
8 |         .map_or(false, |cfg| cfg.split(',').find(|&f| f == "sse2").is_some());
  |          ^^^^^^ help: there is a method with a similar name: `map_err`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `glam`.
warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by ToastyMod** [comment]
False alarm, it was my rustc version whoops.

**Comment by bitshifter** [comment]
I should probably bump the minimum rust version in cargo though so thanks for letting me know.

**Comment by ToastyMod** [comment]
No prob yo

**Comment by bitshifter** [comment]
Turns out setting the minimum supported Rust version isn't a feature of cargo yet.

**Comment by hube12** [comment]
There should definetly be a warning, kinda throw me off for a bit, thanks for the issue tho ;)

**Comment by bitshifter** [comment]
I'll reopen this so I don't forget to try do something about it.
