### ISSUE TITLE
Modifying individual elements of a Mat2 is very awkward

### ISSUE THREAD

**Issue by hrydgard** [bitshifter/glam-rs#60]
Presumably the same goes for the other matrix sizes.

The natural thing would seem to be:
```
my_matrix.x_axis().set_y(xy_value);
```
However, this does not work, as x_axis() does not return a mutable reference. You have to, as far as I can tell:

```
let mut x_axis = my_matrix.x_axis();
x_axis.set_y(xy_value);
my_matrix.set_x_axis(x_axis);
```

This is of course quite awkward. I'm not sure how you'd like the interface to look, so I haven't made a PR.

There's some commented-out accessors col and col_mut which seem like they would do the trick.

**Comment by bitshifter** [comment]
I added `Vec3::x_mut` which returns `&mut 32` so it probably makes sense to add `Mat2::x_axis_mut` which returns `&mut Vec2` etc.

So the above code would look like:

```
my_maxtrix.x_axis_mut().y_mut() = xy_value;
```

or if you prefer

```
my_maxtrix.x_axis_mut().set_y(xy_value);
```

I added the column accessors a while ago but then wasn't sure how much people would be modifying individual elements of matrices, but if people are doing that and would find them useful I can uncomment them. The main difference with the column accessors being that they use indices, so possibly higher overhead than accessing an explicit axis. I have seen some people using indices to set vector elements and added index operators to better support that, but didn't go as far as doing the same for matrices.

**Comment by hrydgard** [comment]
I just had a use case (that didn't need indexing) but this indeed is needed pretty rarely. 

I think `my_matrix.x_axis_mut().y_mut() = xy_value;` would be totally acceptable for how uncommon it is to need it, and already a large improvement.

**Comment by hrydgard** [comment]
Thanks!
