### ISSUE TITLE
Add an affine transform matrix type.

### ISSUE THREAD

**Issue by cessen** [bitshifter/glam-rs#62]
I've been poking at Psychopath a bit again, and I realized that in the context of a ray tracer you pretty much never need full projective transforms, you only need affine transforms.  And this presents a lot of opportunities for optimization:

* An affine transform matrix only needs to store 4x3 floats, not 4x4, because the fourth row is implicitly known.
* Transforming points/vectors can be further optimized due to the statically-known implicit fourth row.
* Matrix inversion can also be further optimized.
* There are tricks for directly performing inverse transforms on points/vectors that are more efficient than fully inverting the matrix + transforming.

I'm mainly filing this issue to find out if this is something you'd be interested in including in Glam.  If so, then when I get some time (which might be a while) I'll take a crack at implementing this.  If not, I'll just create my own custom type in Psychopath.

**Comment by bitshifter** [comment]
Hey there! Yep, this is definitely something I was interested in. Maybe add the information above as a comment on #25 and I'll close this. It's probably useful to keep the context of the other approaches I was looking at in #25 which didn't really pan out. I'm still interested in adding something that is a bit more special purpose than a 4x4 matrix.
