### ISSUE TITLE
Consider providing SIMD `From` conversions for mask types

### ISSUE THREAD

**Issue by jbrd** [bitshifter/glam-rs#63]
Hi, and thanks for writing this amazing library! I have been using it in some projects and have occasionally needed to write some SIMD intrinsics that operate directly on the SIMD types in this library. You can do it now in a messy way with unsafe raw pointer casts, but it feels a little unnecessary. It would be super useful to make the struct members that are currently marked as `pub(crate)` just `pub`, so that the underlying SIMD types could be easily accessed directly. 

I guess the downside to this is that depending on which configuration you are using to build the library, you would end up with different struct members. In practice, this would mean the caller would also have to gate their code on the build configuration, but this seems reasonable to me. But if this is a step too far, then perhaps an alternative approach would be to add an extra "direct access" trait for the SIMD types only?

Is this something that could be considered? If so, I'd be happy to prepare a contribution, if you could provide some guidance on what approach fits best.

**Comment by bitshifter** [comment]
Hi, good to hear you are looking glam! You should already be able to convert between `Vec4`, `Vec3` and `__m128` using existing `From` implementations. See https://docs.rs/glam/0.8.7/src/glam/f32/vec4.rs.html#70-86.

Does that do what you need?

**Comment by jbrd** [comment]
Thanks for such a fast response, and yes, sorry, I should have checked that - it does indeed look like the existing `From` conversions satisfy this in general. In my case though, I have a mask type (e.g. `Vec3Mask`) and need access to the underlying `__m128`, so I think this could be solved quite nicely by just adding the necessary `From` conversions to the mask types too...

**Comment by bitshifter** [comment]
No worries. The trait implementations aren't really very obvious in Rust docs so if you think there's somewhere else where I could make it clearer that this can be done in the docs let me know.

I would be happy to add a convert from `Vec4Mask` and `Vec3Mask` to `__m128` but the other way around is a little problematic. The mask types expect the input to be `0xffffffff` or `0x0` in each lane and if they are not things like the select give what might be an unexpected result. So converting from any old `__m128` may cause problems. Do you have a need to go from `__m128` to `VecNMask` or just from `VecNMask` to `__m128`?

**Comment by jbrd** [comment]
That would be really useful, thanks - I think just going from a mask to a `__m128` would actually be sufficient, since you could go the other way by using the existing `From` conversion to go from a `__m128` to a `Vec`, and then use the comparison functions to get you back to a mask - with the comparison functions guaranteeing valid mask values (`0x0` / `0xffffffff`).
