### ISSUE TITLE
Couple Missing Trait Impls on Vec3A

### ISSUE THREAD

**Issue by cwfitzgerald** [bitshifter/glam-rs#66]
I'm migrating to 0.9 from 0.8, and personally I love the split between the Vec3 and Vec3A. I came across a couple issues however with Vec3A not having impls for some operations. For example, `Mat3 * Vec3A` doesn't compile, functions that take a `Vec3` don't have versions for Vec3A (though I can .into() it, it seems silly to be constantly converting).

I'm not sure what exactly the right solution to this, but it's a pretty big ergonomics issue, when I kinda expect to be able to do `/s/Vec3/Vec3A/` in my source code to transition from 0.8 to 0.9.

**Comment by bitshifter** [comment]
Hey, thanks for the report.

Would you be able to post snippets of things that don't compile, maybe with a bit of surrounding context?

In particular I wasn't sure how much people would be using `Mat3` so that is a bit of an oversight on my part.

**Comment by bitshifter** [comment]
Looking at mat3 maybe it's just the multiply that needs to be added

**Comment by bitshifter** [comment]
I'll do a release tomorrow, you could try git and see if that is working for you.

**Comment by cwfitzgerald** [comment]
Updated to latest git, and indeed matrices work as expected!

Some context to my mat3 use:

https://github.com/BVE-Reborn/bve-reborn/blob/glam/bve/src/load/mesh/execution.rs#L235-L249

The only thing really remaining are things like look_at_lh which take Vec3, but I think it's perfectly reasonable to do conversions in places like this, so it's fine. The matrix situation (which would require two conversions) was the main issue.

https://github.com/BVE-Reborn/bve-reborn/blob/glam/bve-render/src/camera.rs#L25-L39

Thanks for the prompt response!

**Comment by bitshifter** [comment]
Ah thanks, it's always useful to see how people are using glam. Possibly in the examples you've linked above it might be easier to use `Vec3`. It's probably only worth switching to `Vec3A` when there is a lot of math going on, unless you are relying on the size being 16 bytes for something.

**Comment by cwfitzgerald** [comment]
Yeah definitely. Thanks for all the help!
