### ISSUE TITLE
Should Quat::mul_vec3 accept Vec3 instead of Vec3A?

### ISSUE THREAD

**Issue by kettle11** [bitshifter/glam-rs#67]
After the recent changes to `Vec3` I encountered a build break because [Quat::mul_vec3 ](https://docs.rs/glam/0.9.1/glam/struct.Quat.html#method.mul_vec3 ) now accepts and returns Vec3A instead of Vec3. 

Is this expected?

**Comment by bitshifter** [comment]
That does sound like an oversight on my part, I will take a look.

**Comment by bitshifter** [comment]
Fixed in git, will publish in a new revision in a day or two

**Comment by bitshifter** [comment]
Publish 0.9.2 with this fix.
