### ISSUE TITLE
to euler angles

### ISSUE THREAD

**Issue by bitshifter** [bitshifter/glam-rs#68]
I have seen some people wanting to extract euler angles from Quaternion and Matrix rotations. Then I've seen others disparaging them for using euler angles. Euler angles are commonly used in editors and while we can create glam rotations from euler angles there's currently no support for going the other way. I don't want to encourage using euler angles where they aren't appropriate but there might be legitimate use cases where providing this functionality would be appropriate.

**Comment by John-Nagle** [comment]
Yes. There's `pub fn from_rotation_ypr(yaw: f32, pitch: f32, roll: f32) -> Self` but not the reverse operation. If you  have one, you should have both, and they should be symmetrical.

**Comment by CAD97** [comment]
See also #79; ypr functionality isn't coordinate agnostic. It is a good idea for however this ends up being handled eventually to be symmetric, though.

**Comment by mickare** [comment]
Hey, I made a pull-request #163 to add conversion between intrinsic Euler rotation sequences and Quaternions.

In the PR, only the three-axis sequences (e.g. YXZ - yaw pitch roll) are tested fully.
The two-axis conversions (e.g. ZxZ) are sometimes ambiguous and cannot be tested with my generic test implementation. Those are marked as deprecated until someone has a nice test for them. Until then, use with caution (also marked as deprecated)!

### Usage
```rust
let q = Quat::from_euler(EulerRot::YXZi, 0.3, 0.1, 0.0);
let (y, x, z) = q.to_euler(EulerRot::YXZi);  // the "i" indicates intrinsic
```

**Comment by bitshifter** [comment]
Thanks @mickare !
