### ISSUE TITLE
Should Vec4 truncate return Vec3 instead of Vec3A

### ISSUE THREAD

**Issue by bitshifter** [bitshifter/glam-rs#69]
I've seen this trip up new users. It is done this way because it's effectively a no-op, but perhaps the default behaviour should be to return Vec3 and provide another method for coverting to Vec3A.

**Comment by aloucks** [comment]
What about renaming `Vec3A` back to `Vec3` and creating an `unaligned` module for non-simd types. Everything would then use `Vec3` by default and `unaligned::Vec3` would be for data load/store (i.e. there would be convenient conversion functions)?

**Comment by bitshifter** [comment]
I would be pretty reluctant to do more significant renaming at this point. Also I think there is limited utility in having a 16 byte aligned `Vec2` or a 4 byte aligned `Vec4`.

**Comment by repi** [comment]
Think it would be cleanest and easiest to understand if it truncated to `Vec3`, could have specific additional function for truncating to a `Vec3A`?

**Comment by ccptr** [comment]
> I would be pretty reluctant to do more significant renaming at this point. Also I think there is limited utility in having a 16 byte aligned `Vec2` or a 4 byte aligned `Vec4`.

I actually came across this issue because I need a 4 byte aligned `Vec4` to interface with a game. It would definitely be nice to have, and I think naming would be more consistent if `Vec4` was renamed to `Vec4A`.

**Comment by aloucks** [comment]
There's no way to `truncate` a `Vec4` to `Vec3A`. 

The documentation says to use `Vec3A::from` but it doesn't exist in `29.2`. 

```
pub fn truncate(self) -> Vec3
/// Creates a 3D vector from the `x`, `y` and `z` elements of `self`, discarding `w`.
///
/// Truncation to [`Vec3`] may also be performed by using [`self.xyz()`][crate::swizzles::Vec4Swizzles::xyz()].
///
/// To truncate to [`Vec3A`] use [`Vec3A::from()`].
```

**Comment by bitshifter** [comment]
There is https://docs.rs/glam/latest/glam/f32/struct.Vec3A.html#method.from_vec4, the docs need updating

**Comment by aloucks** [comment]
> There is https://docs.rs/glam/latest/glam/f32/struct.Vec3A.html#method.from_vec4, the docs need updating

Not sure how I missed that, but thank you!
