### ISSUE TITLE
Support f64 and i32

### ISSUE THREAD

**Issue by bitshifter** [bitshifter/glam-rs#70]
Once the glam API is stable (e.g. 1.0) I think it would make sense to add support for f64 and i32. I still would avoid using generics, since I couldn't easily provide SIMD implementation without specialisation, and even if specialisation was available it would complicate the API using generics. So perhaps some macros behind the scenes or just copy and paste. A lot of functionality is pretty simple so I don't think duplication is the end of the world, once the API is stable.

**Comment by bitshifter** [comment]
Primarily thinking of adding the following initially:

* `IVec2`, `IVec3` - these should be able to use the existing `Vec2Mask` and `Vec3Mask` types.
* for `f64` I would support everything you can do in `f32` but SIMD would not be a high priority.

The other question is how to implement them behind the scenes. More code duplication? Macros? Learn to love generics? Certainly the easy approach to get it done is code duplication but it will become unmanageable eventually. So probably macros.

**Comment by bitshifter** [comment]
Current status of this has been done as part of #99 but I still have some things to tidy up.

**Comment by damccull** [comment]
Is there a reason i64 and u64 were not included in the intergers?
