### ISSUE TITLE
Unnecessary handedness in rotation explanation

### ISSUE THREAD

**Issue by emilk** [bitshifter/glam-rs#78]
In the landing page of the documentation at https://docs.rs/glam you can read the following:

> Rotations follow left-hand rule. The direction of the axis gives the direction of rotation: with the left thumb pointing in the positive direction of the axis the left fingers curl around the axis in the direction of the rotation.

Then follows his code:

``` rust
// rotate +x 90 degrees clockwise around y giving -z
let m = Mat3::from_rotation_y(90.0_f32.to_radians());
let v = m * Vec3::unit_x();
assert!(v.abs_diff_eq(-Vec3::unit_z(), core::f32::EPSILON));
```

The thing is: quarternion rotations are not tied to any frame or handedness. For left-handed coordinate systems it follows left-hand rule, and for right-handed coordinate systems it follows right-hand rule. Consider a right handed X-Y-Z system. 90 deg rotation around Y would bring +X to the -Z direction, just like the example above.

So the above paragraph muddies the waters and may unnecessarily scare away people who use right-handed systems.

SUMMARY: glam is (mostly) handedness agnostic. I think it would help the project to say so up-front, instead of implying the opposite!

**Comment by bitshifter** [comment]
Ah right, handedness has confused me a bit at points. I guess looking at https://www.evl.uic.edu/ralph/508S98/coordinates.html it's more about the convention than what is going on in the math.

**Comment by bitshifter** [comment]
If you felt like rewording it I'd be happy to accept a PR. Otherwise I will get to it sometime.

**Comment by aloucks** [comment]
For what it's worth, I found the documentation helpful and hope that it's not removed. Wouldn't the angles need to be negated if the rotations were following the right-hand rule?

**Comment by bitshifter** [comment]
> Wouldn't the angles need to be negated if the rotations were following the right-hand rule?

I don't think so, only for a function like `from_rotation_ypr` which bakes in a notion of coordinate systems (see #79). If you look at the  images on https://www.evl.uic.edu/ralph/508S98/coordinates.html rotating unit +Z +90 degrees around +Y will result in unit +X. This is true for both left-handed and right-handed systems. While conceptually in the left-handed system positive rotation is clockwise and in the right-handed system positive rotation is counter-clockwise, mathematically they are the same.

I think that is what @emilk was getting at.

Code wise:

```rust
use glam::{Mat3, Vec3};
// rotate +z 90 degrees clockwise around y giving +x
let m = Mat3::from_rotation_y(90.0_f32.to_radians());
let v = m * Vec3::unit_z();
assert!(v.abs_diff_eq(Vec3::unit_x(), core::f32::EPSILON));
```

**Comment by emilk** [comment]
Thanks @bitshifter !
