### ISSUE TITLE
impl Add<Quat> and Sub<Quat> for Quat

### ISSUE THREAD

**Issue by iwikal** [bitshifter/glam-rs#82]
In short: Through a somewhat complicated chain of traits and supertraits in multiple different libraries, I've found myself needing glam::Quat to implement addition and subtraction. I've started working on a PR.

In long: I'm trying to implement skeletal animation for the bevy engine. They use glam, and rotations are represented by your quaternions. We're looking to use the splines crate to handle interpolation between keyframes, which is a very generic crate. It does however require the supplied type to implement addition and subtraction, and through a shim I've managed to get it working, but at the cost of user convenience. The splines crate provides implementations of its traits for a number of external math crates, but I am unable to add support for glam because of the requirement of these ops.

I understand that adding support for addition and subtraction ops might mislead users who are trying to combine rotations, but perhaps with good documentation we can mitigate this risk and steer them towards correct usage.

**Comment by bitshifter** [comment]
Hi there, is the code you are describing public? It would be good to try and get a better understanding of your use case.

**Comment by iwikal** [comment]
This is what I would like to add to splines:
https://github.com/phaazon/splines/pull/50

To aid this pull request in Bevy:
https://github.com/bevyengine/bevy/pull/482

**Comment by iwikal** [comment]
It turns out, for this to work, Quat needs Mul<f32> and Div<f32> too.

**Comment by bitshifter** [comment]
Thanks, I will take a look when I get the time. I want to check a few other math libraries to see if they provide theses operators in quaternions as well.

**Comment by iwikal** [comment]
cgmath and nalgebra both do.

**Comment by bitshifter** [comment]
OK, I checked DirectXTK's SimpleMath and GLM, they also support these. It's not something I've really come across so just wanted to check.
