### ISSUE TITLE
Migrate from Travis to GitHub Actions

### ISSUE THREAD

**Issue by bitshifter** [bitshifter/glam-rs#84]
Having a github action for cargo deny seems to have broken travis builds for PRs, which is unfortunate. I think most likely the simplest thing to do is to migrate entirely to github actions. Also needs to work with code coverage.

Edit: the travis builds still happen for PRs but they don't appear in GitHub, at least they don't on success.

**Comment by XAMPPRocky** [comment]
I can work on this, this week.
