### ISSUE TITLE
Getting raw bytes from Vec<Mat4>

### ISSUE THREAD

**Issue by FredrikNoren** [bitshifter/glam-rs#87]
Hi,

I'm probably missing something but I can't figure out how to turn a `Vec<Mat4>` into a `&[u8]`, which wgpu needs?

**Comment by bitshifter** [comment]
I think a lot of people are using the `bytemuck` crate for this purpose, it is not something that `glam` currently supports, but it would be easy to add it as an optional feature.

**Comment by FredrikNoren** [comment]
@bitshifter Yeah I was trying to do it with bytemuck but as far as I can tell it requires two traits two be implemented (bytemuck::Pod and Zeroable). I ended up wrapping my Mat4 in another type so that I could use bytemuck on it. Not really sure what the best solution is here though

**Comment by aloucks** [comment]
Have you tried using [AsRef<[f32; 16]>](https://docs.rs/glam/0.9.5/glam/struct.Mat4.html#impl-AsRef%3C%5Bf32%3B%2016%5D%3E) and [cast_slice](https://docs.rs/bytemuck/1.4.1/bytemuck/fn.cast_slice.html) ?

**Comment by FredrikNoren** [comment]
@aloucks Yeah I've used that when I just have one Mat4, but in this case I have a Vec of them, so I don't think it's possible then right?

**Comment by aloucks** [comment]
@FredrikNoren I'm not sure. You could always use [`std::slice::from_raw_parts`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html) if bytemuck isn't working out.
