### ISSUE TITLE
Vec SIMD types are not understood by rust-analyzer without a workaround

### ISSUE THREAD

**Issue by hrydgard** [bitshifter/glam-rs#95]
See https://github.com/rust-analyzer/rust-analyzer/issues/6556 , causing:

![ra-repro](https://user-images.githubusercontent.com/130929/99182699-c6aee500-2736-11eb-8044-2dd6448a1a0c.png)

I wonder if there's a way to make rust-analyzer understand which implementation should be looked at without involving a `build.rs`...

**Comment by bitshifter** [comment]
Thanks for the report. I had seen people having problems with this but didn't know what the cause was. I am looking at doing a bit of an internal refactor to make it easier to add support for other ISAs and to support other scalar types, so possibly the changes I have in mind will help with this.
